/**
 *
 *  TodoController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "TodoController.h"
#include <string>


void TodoController::getOne(const HttpRequestPtr &req,
                            std::function<void(const HttpResponsePtr &)> &&callback,
                            std::string &&id)
{
}

#include "models/Todo.h"

void TodoController::get(const HttpRequestPtr &req,
                         std::function<void(const HttpResponsePtr &)> &&callback)
{
    auto dbClient = app().getDbClient();
    drogon::orm::Mapper<drogon_model::admingas::Todo> mp(dbClient);
    
    try {
        auto todos = mp.findAll();
        Json::Value ret(Json::arrayValue);
        for (auto const &todo : todos) {
            ret.append(todo.toJson());
        }
        auto resp = HttpResponse::newHttpJsonResponse(ret);
        callback(resp);
    } catch (const drogon::orm::DrogonDbException &e) {
        Json::Value error;
        error["error"] = e.base().what();
        auto resp = HttpResponse::newHttpJsonResponse(error);
        resp->setStatusCode(k500InternalServerError);
        callback(resp);
    }
}
void TodoController::create(const HttpRequestPtr &req,
                            std::function<void(const HttpResponsePtr &)> &&callback)
{
    auto jsonPtr = req->getJsonObject();
    if (!jsonPtr) {
        auto resp = HttpResponse::newHttpResponse();
        resp->setStatusCode(k400BadRequest);
        callback(resp);
        return;
    }
    
    drogon_model::admingas::Todo todo;
    todo.updateByJson(*jsonPtr);
    
    auto dbClient = app().getDbClient();
    drogon::orm::Mapper<drogon_model::admingas::Todo> mp(dbClient);
    try {
        mp.insert(todo);
        auto resp = HttpResponse::newHttpJsonResponse(todo.toJson());
        callback(resp);
    } catch (const drogon::orm::DrogonDbException &e) {
        Json::Value error;
        error["error"] = e.base().what();
        auto resp = HttpResponse::newHttpJsonResponse(error);
        resp->setStatusCode(k500InternalServerError);
        callback(resp);
    }
}
void TodoController::updateOne(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback,
                               std::string &&id)
{
    auto jsonPtr = req->getJsonObject();
    if (!jsonPtr) {
        auto resp = HttpResponse::newHttpResponse();
        resp->setStatusCode(k400BadRequest);
        callback(resp);
        return;
    }

    auto dbClient = app().getDbClient();
    drogon::orm::Mapper<drogon_model::admingas::Todo> mp(dbClient);
    try {
        auto todo = mp.findByPrimaryKey(std::stoi(id));
        todo.updateByJson(*jsonPtr);
        mp.update(todo);
        auto resp = HttpResponse::newHttpJsonResponse(todo.toJson());
        callback(resp);
    } catch (const drogon::orm::DrogonDbException &e) {
        Json::Value error;
        error["error"] = e.base().what();
        auto resp = HttpResponse::newHttpJsonResponse(error);
        resp->setStatusCode(k500InternalServerError);
        callback(resp);
    }
}

/*
void TodoController::update(const HttpRequestPtr &req,
                            std::function<void(const HttpResponsePtr &)> &&callback)
{

}*/

void TodoController::deleteOne(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback,
                               std::string &&id)
{
    auto dbClient = app().getDbClient();
    drogon::orm::Mapper<drogon_model::admingas::Todo> mp(dbClient);
    try {
        mp.deleteByPrimaryKey(std::stoi(id));
        Json::Value ret;
        ret["success"] = true;
        auto resp = HttpResponse::newHttpJsonResponse(ret);
        callback(resp);
    } catch (const drogon::orm::DrogonDbException &e) {
        Json::Value error;
        error["error"] = e.base().what();
        auto resp = HttpResponse::newHttpJsonResponse(error);
        resp->setStatusCode(k500InternalServerError);
        callback(resp);
    }
}
