/**
 *
 *  TodoController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
using namespace drogon;
/**
 * @brief this class is created by the drogon_ctl command (drogon_ctl create controller -r TodoController).
 * this class is a restful API controller.
 */
class TodoController: public drogon::HttpController<TodoController>
{
  public:
    METHOD_LIST_BEGIN
    // use METHOD_ADD to add your custom processing function here;
    ADD_METHOD_TO(TodoController::getOne,"/todo/{1}",Get,Options);
    ADD_METHOD_TO(TodoController::get,"/todo",Get,Options);
    ADD_METHOD_TO(TodoController::create,"/todo",Post,Options);
    ADD_METHOD_TO(TodoController::updateOne,"/todo/{1}",Put,Options);
    ADD_METHOD_TO(TodoController::deleteOne,"/todo/{1}",Delete,Options);
    METHOD_LIST_END

    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                std::string &&id);
    void updateOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                std::string &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   std::string &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback);

//    void update(const HttpRequestPtr &req,
//                std::function<void(const HttpResponsePtr &)> &&callback);

};
