/**
 *
 *  Concepto.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Concepto.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::admingas;

const std::string Concepto::Cols::_id = "\"id\"";
const std::string Concepto::Cols::_clave_prod_serv = "\"clave_prod_serv\"";
const std::string Concepto::Cols::_clave_unidad = "\"clave_unidad\"";
const std::string Concepto::Cols::_descripcion = "\"descripcion\"";
const std::string Concepto::Cols::_valor_unitario = "\"valor_unitario\"";
const std::string Concepto::primaryKeyName = "id";
const bool Concepto::hasPrimaryKey = true;
const std::string Concepto::tableName = "\"concepto\"";

const std::vector<typename Concepto::MetaData> Concepto::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"clave_prod_serv","std::string","character varying",8,0,0,1},
{"clave_unidad","std::string","character varying",3,0,0,1},
{"descripcion","std::string","character varying",255,0,0,1},
{"valor_unitario","double","double precision",8,0,0,1}
};
const std::string &Concepto::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Concepto::Concepto(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["clave_prod_serv"].isNull())
        {
            claveProdServ_=std::make_shared<std::string>(r["clave_prod_serv"].as<std::string>());
        }
        if(!r["clave_unidad"].isNull())
        {
            claveUnidad_=std::make_shared<std::string>(r["clave_unidad"].as<std::string>());
        }
        if(!r["descripcion"].isNull())
        {
            descripcion_=std::make_shared<std::string>(r["descripcion"].as<std::string>());
        }
        if(!r["valor_unitario"].isNull())
        {
            valorUnitario_=std::make_shared<double>(r["valor_unitario"].as<double>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            claveProdServ_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            claveUnidad_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            descripcion_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            valorUnitario_=std::make_shared<double>(r[index].as<double>());
        }
    }

}

Concepto::Concepto(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            claveProdServ_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            claveUnidad_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            descripcion_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            valorUnitario_=std::make_shared<double>(pJson[pMasqueradingVector[4]].asDouble());
        }
    }
}

Concepto::Concepto(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("clave_prod_serv"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["clave_prod_serv"].isNull())
        {
            claveProdServ_=std::make_shared<std::string>(pJson["clave_prod_serv"].asString());
        }
    }
    if(pJson.isMember("clave_unidad"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["clave_unidad"].isNull())
        {
            claveUnidad_=std::make_shared<std::string>(pJson["clave_unidad"].asString());
        }
    }
    if(pJson.isMember("descripcion"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["descripcion"].isNull())
        {
            descripcion_=std::make_shared<std::string>(pJson["descripcion"].asString());
        }
    }
    if(pJson.isMember("valor_unitario"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["valor_unitario"].isNull())
        {
            valorUnitario_=std::make_shared<double>(pJson["valor_unitario"].asDouble());
        }
    }
}

void Concepto::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            claveProdServ_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            claveUnidad_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            descripcion_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            valorUnitario_=std::make_shared<double>(pJson[pMasqueradingVector[4]].asDouble());
        }
    }
}

void Concepto::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("clave_prod_serv"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["clave_prod_serv"].isNull())
        {
            claveProdServ_=std::make_shared<std::string>(pJson["clave_prod_serv"].asString());
        }
    }
    if(pJson.isMember("clave_unidad"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["clave_unidad"].isNull())
        {
            claveUnidad_=std::make_shared<std::string>(pJson["clave_unidad"].asString());
        }
    }
    if(pJson.isMember("descripcion"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["descripcion"].isNull())
        {
            descripcion_=std::make_shared<std::string>(pJson["descripcion"].asString());
        }
    }
    if(pJson.isMember("valor_unitario"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["valor_unitario"].isNull())
        {
            valorUnitario_=std::make_shared<double>(pJson["valor_unitario"].asDouble());
        }
    }
}

const int32_t &Concepto::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Concepto::getId() const noexcept
{
    return id_;
}
void Concepto::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Concepto::PrimaryKeyType & Concepto::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Concepto::getValueOfClaveProdServ() const noexcept
{
    static const std::string defaultValue = std::string();
    if(claveProdServ_)
        return *claveProdServ_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Concepto::getClaveProdServ() const noexcept
{
    return claveProdServ_;
}
void Concepto::setClaveProdServ(const std::string &pClaveProdServ) noexcept
{
    claveProdServ_ = std::make_shared<std::string>(pClaveProdServ);
    dirtyFlag_[1] = true;
}
void Concepto::setClaveProdServ(std::string &&pClaveProdServ) noexcept
{
    claveProdServ_ = std::make_shared<std::string>(std::move(pClaveProdServ));
    dirtyFlag_[1] = true;
}

const std::string &Concepto::getValueOfClaveUnidad() const noexcept
{
    static const std::string defaultValue = std::string();
    if(claveUnidad_)
        return *claveUnidad_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Concepto::getClaveUnidad() const noexcept
{
    return claveUnidad_;
}
void Concepto::setClaveUnidad(const std::string &pClaveUnidad) noexcept
{
    claveUnidad_ = std::make_shared<std::string>(pClaveUnidad);
    dirtyFlag_[2] = true;
}
void Concepto::setClaveUnidad(std::string &&pClaveUnidad) noexcept
{
    claveUnidad_ = std::make_shared<std::string>(std::move(pClaveUnidad));
    dirtyFlag_[2] = true;
}

const std::string &Concepto::getValueOfDescripcion() const noexcept
{
    static const std::string defaultValue = std::string();
    if(descripcion_)
        return *descripcion_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Concepto::getDescripcion() const noexcept
{
    return descripcion_;
}
void Concepto::setDescripcion(const std::string &pDescripcion) noexcept
{
    descripcion_ = std::make_shared<std::string>(pDescripcion);
    dirtyFlag_[3] = true;
}
void Concepto::setDescripcion(std::string &&pDescripcion) noexcept
{
    descripcion_ = std::make_shared<std::string>(std::move(pDescripcion));
    dirtyFlag_[3] = true;
}

const double &Concepto::getValueOfValorUnitario() const noexcept
{
    static const double defaultValue = double();
    if(valorUnitario_)
        return *valorUnitario_;
    return defaultValue;
}
const std::shared_ptr<double> &Concepto::getValorUnitario() const noexcept
{
    return valorUnitario_;
}
void Concepto::setValorUnitario(const double &pValorUnitario) noexcept
{
    valorUnitario_ = std::make_shared<double>(pValorUnitario);
    dirtyFlag_[4] = true;
}

void Concepto::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Concepto::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "clave_prod_serv",
        "clave_unidad",
        "descripcion",
        "valor_unitario"
    };
    return inCols;
}

void Concepto::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getClaveProdServ())
        {
            binder << getValueOfClaveProdServ();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getClaveUnidad())
        {
            binder << getValueOfClaveUnidad();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDescripcion())
        {
            binder << getValueOfDescripcion();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getValorUnitario())
        {
            binder << getValueOfValorUnitario();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Concepto::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void Concepto::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getClaveProdServ())
        {
            binder << getValueOfClaveProdServ();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getClaveUnidad())
        {
            binder << getValueOfClaveUnidad();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDescripcion())
        {
            binder << getValueOfDescripcion();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getValorUnitario())
        {
            binder << getValueOfValorUnitario();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Concepto::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getClaveProdServ())
    {
        ret["clave_prod_serv"]=getValueOfClaveProdServ();
    }
    else
    {
        ret["clave_prod_serv"]=Json::Value();
    }
    if(getClaveUnidad())
    {
        ret["clave_unidad"]=getValueOfClaveUnidad();
    }
    else
    {
        ret["clave_unidad"]=Json::Value();
    }
    if(getDescripcion())
    {
        ret["descripcion"]=getValueOfDescripcion();
    }
    else
    {
        ret["descripcion"]=Json::Value();
    }
    if(getValorUnitario())
    {
        ret["valor_unitario"]=getValueOfValorUnitario();
    }
    else
    {
        ret["valor_unitario"]=Json::Value();
    }
    return ret;
}

std::string Concepto::toString() const
{
    return toJson().toStyledString();
}

Json::Value Concepto::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 5)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getClaveProdServ())
            {
                ret[pMasqueradingVector[1]]=getValueOfClaveProdServ();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getClaveUnidad())
            {
                ret[pMasqueradingVector[2]]=getValueOfClaveUnidad();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getDescripcion())
            {
                ret[pMasqueradingVector[3]]=getValueOfDescripcion();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getValorUnitario())
            {
                ret[pMasqueradingVector[4]]=getValueOfValorUnitario();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getClaveProdServ())
    {
        ret["clave_prod_serv"]=getValueOfClaveProdServ();
    }
    else
    {
        ret["clave_prod_serv"]=Json::Value();
    }
    if(getClaveUnidad())
    {
        ret["clave_unidad"]=getValueOfClaveUnidad();
    }
    else
    {
        ret["clave_unidad"]=Json::Value();
    }
    if(getDescripcion())
    {
        ret["descripcion"]=getValueOfDescripcion();
    }
    else
    {
        ret["descripcion"]=Json::Value();
    }
    if(getValorUnitario())
    {
        ret["valor_unitario"]=getValueOfValorUnitario();
    }
    else
    {
        ret["valor_unitario"]=Json::Value();
    }
    return ret;
}

bool Concepto::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("clave_prod_serv"))
    {
        if(!validJsonOfField(1, "clave_prod_serv", pJson["clave_prod_serv"], err, true))
            return false;
    }
    else
    {
        err="The clave_prod_serv column cannot be null";
        return false;
    }
    if(pJson.isMember("clave_unidad"))
    {
        if(!validJsonOfField(2, "clave_unidad", pJson["clave_unidad"], err, true))
            return false;
    }
    else
    {
        err="The clave_unidad column cannot be null";
        return false;
    }
    if(pJson.isMember("descripcion"))
    {
        if(!validJsonOfField(3, "descripcion", pJson["descripcion"], err, true))
            return false;
    }
    else
    {
        err="The descripcion column cannot be null";
        return false;
    }
    if(pJson.isMember("valor_unitario"))
    {
        if(!validJsonOfField(4, "valor_unitario", pJson["valor_unitario"], err, true))
            return false;
    }
    else
    {
        err="The valor_unitario column cannot be null";
        return false;
    }
    return true;
}
bool Concepto::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Concepto::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("clave_prod_serv"))
    {
        if(!validJsonOfField(1, "clave_prod_serv", pJson["clave_prod_serv"], err, false))
            return false;
    }
    if(pJson.isMember("clave_unidad"))
    {
        if(!validJsonOfField(2, "clave_unidad", pJson["clave_unidad"], err, false))
            return false;
    }
    if(pJson.isMember("descripcion"))
    {
        if(!validJsonOfField(3, "descripcion", pJson["descripcion"], err, false))
            return false;
    }
    if(pJson.isMember("valor_unitario"))
    {
        if(!validJsonOfField(4, "valor_unitario", pJson["valor_unitario"], err, false))
            return false;
    }
    return true;
}
bool Concepto::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Concepto::validJsonOfField(size_t index,
                                const std::string &fieldName,
                                const Json::Value &pJson,
                                std::string &err,
                                bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 8)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 8)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 3)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 3)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
