/**
 *
 *  Emisor.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace admingas
{

class Emisor
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _rfc;
        static const std::string _nombre;
        static const std::string _regimen_fiscal;
        static const std::string _certificado;
        static const std::string _llave;
        static const std::string _certificado_nombre;
        static const std::string _llave_nombre;
        static const std::string _llave_password;
        static const std::string _certificado_valido_desde;
        static const std::string _certificado_valido_hasta;
        static const std::string _certificado_numero;
        static const std::string _domicilio_fiscal;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Emisor(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Emisor(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Emisor(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Emisor() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int32_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int32_t &pId) noexcept;

    /**  For column rfc  */
    ///Get the value of the column rfc, returns the default value if the column is null
    const std::string &getValueOfRfc() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRfc() const noexcept;
    ///Set the value of the column rfc
    void setRfc(const std::string &pRfc) noexcept;
    void setRfc(std::string &&pRfc) noexcept;

    /**  For column nombre  */
    ///Get the value of the column nombre, returns the default value if the column is null
    const std::string &getValueOfNombre() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getNombre() const noexcept;
    ///Set the value of the column nombre
    void setNombre(const std::string &pNombre) noexcept;
    void setNombre(std::string &&pNombre) noexcept;

    /**  For column regimen_fiscal  */
    ///Get the value of the column regimen_fiscal, returns the default value if the column is null
    const std::string &getValueOfRegimenFiscal() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRegimenFiscal() const noexcept;
    ///Set the value of the column regimen_fiscal
    void setRegimenFiscal(const std::string &pRegimenFiscal) noexcept;
    void setRegimenFiscal(std::string &&pRegimenFiscal) noexcept;

    /**  For column certificado  */
    ///Get the value of the column certificado, returns the default value if the column is null
    const std::string &getValueOfCertificado() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCertificado() const noexcept;
    ///Set the value of the column certificado
    void setCertificado(const std::string &pCertificado) noexcept;
    void setCertificado(std::string &&pCertificado) noexcept;
    void setCertificadoToNull() noexcept;

    /**  For column llave  */
    ///Get the value of the column llave, returns the default value if the column is null
    const std::string &getValueOfLlave() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getLlave() const noexcept;
    ///Set the value of the column llave
    void setLlave(const std::string &pLlave) noexcept;
    void setLlave(std::string &&pLlave) noexcept;
    void setLlaveToNull() noexcept;

    /**  For column certificado_nombre  */
    ///Get the value of the column certificado_nombre, returns the default value if the column is null
    const std::string &getValueOfCertificadoNombre() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCertificadoNombre() const noexcept;
    ///Set the value of the column certificado_nombre
    void setCertificadoNombre(const std::string &pCertificadoNombre) noexcept;
    void setCertificadoNombre(std::string &&pCertificadoNombre) noexcept;
    void setCertificadoNombreToNull() noexcept;

    /**  For column llave_nombre  */
    ///Get the value of the column llave_nombre, returns the default value if the column is null
    const std::string &getValueOfLlaveNombre() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getLlaveNombre() const noexcept;
    ///Set the value of the column llave_nombre
    void setLlaveNombre(const std::string &pLlaveNombre) noexcept;
    void setLlaveNombre(std::string &&pLlaveNombre) noexcept;
    void setLlaveNombreToNull() noexcept;

    /**  For column llave_password  */
    ///Get the value of the column llave_password, returns the default value if the column is null
    const std::string &getValueOfLlavePassword() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getLlavePassword() const noexcept;
    ///Set the value of the column llave_password
    void setLlavePassword(const std::string &pLlavePassword) noexcept;
    void setLlavePassword(std::string &&pLlavePassword) noexcept;
    void setLlavePasswordToNull() noexcept;

    /**  For column certificado_valido_desde  */
    ///Get the value of the column certificado_valido_desde, returns the default value if the column is null
    const ::trantor::Date &getValueOfCertificadoValidoDesde() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCertificadoValidoDesde() const noexcept;
    ///Set the value of the column certificado_valido_desde
    void setCertificadoValidoDesde(const ::trantor::Date &pCertificadoValidoDesde) noexcept;
    void setCertificadoValidoDesdeToNull() noexcept;

    /**  For column certificado_valido_hasta  */
    ///Get the value of the column certificado_valido_hasta, returns the default value if the column is null
    const ::trantor::Date &getValueOfCertificadoValidoHasta() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCertificadoValidoHasta() const noexcept;
    ///Set the value of the column certificado_valido_hasta
    void setCertificadoValidoHasta(const ::trantor::Date &pCertificadoValidoHasta) noexcept;
    void setCertificadoValidoHastaToNull() noexcept;

    /**  For column certificado_numero  */
    ///Get the value of the column certificado_numero, returns the default value if the column is null
    const std::string &getValueOfCertificadoNumero() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCertificadoNumero() const noexcept;
    ///Set the value of the column certificado_numero
    void setCertificadoNumero(const std::string &pCertificadoNumero) noexcept;
    void setCertificadoNumero(std::string &&pCertificadoNumero) noexcept;
    void setCertificadoNumeroToNull() noexcept;

    /**  For column domicilio_fiscal  */
    ///Get the value of the column domicilio_fiscal, returns the default value if the column is null
    const std::string &getValueOfDomicilioFiscal() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDomicilioFiscal() const noexcept;
    ///Set the value of the column domicilio_fiscal
    void setDomicilioFiscal(const std::string &pDomicilioFiscal) noexcept;
    void setDomicilioFiscal(std::string &&pDomicilioFiscal) noexcept;
    void setDomicilioFiscalToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 13;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Emisor>;
    friend drogon::orm::BaseBuilder<Emisor, true, true>;
    friend drogon::orm::BaseBuilder<Emisor, true, false>;
    friend drogon::orm::BaseBuilder<Emisor, false, true>;
    friend drogon::orm::BaseBuilder<Emisor, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Emisor>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> id_;
    std::shared_ptr<std::string> rfc_;
    std::shared_ptr<std::string> nombre_;
    std::shared_ptr<std::string> regimenFiscal_;
    std::shared_ptr<std::string> certificado_;
    std::shared_ptr<std::string> llave_;
    std::shared_ptr<std::string> certificadoNombre_;
    std::shared_ptr<std::string> llaveNombre_;
    std::shared_ptr<std::string> llavePassword_;
    std::shared_ptr<::trantor::Date> certificadoValidoDesde_;
    std::shared_ptr<::trantor::Date> certificadoValidoHasta_;
    std::shared_ptr<std::string> certificadoNumero_;
    std::shared_ptr<std::string> domicilioFiscal_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[13]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "rfc,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "nombre,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "regimen_fiscal,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "certificado,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "llave,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "certificado_nombre,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "llave_nombre,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "llave_password,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "certificado_valido_desde,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "certificado_valido_hasta,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "certificado_numero,";
            ++parametersCount;
        }
        if(dirtyFlag_[12])
        {
            sql += "domicilio_fiscal,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[12])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace admingas
} // namespace drogon_model
