/**
 *
 *  Emisor.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Emisor.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::admingas;

const std::string Emisor::Cols::_id = "\"id\"";
const std::string Emisor::Cols::_rfc = "\"rfc\"";
const std::string Emisor::Cols::_nombre = "\"nombre\"";
const std::string Emisor::Cols::_regimen_fiscal = "\"regimen_fiscal\"";
const std::string Emisor::Cols::_certificado = "\"certificado\"";
const std::string Emisor::Cols::_llave = "\"llave\"";
const std::string Emisor::Cols::_certificado_nombre = "\"certificado_nombre\"";
const std::string Emisor::Cols::_llave_nombre = "\"llave_nombre\"";
const std::string Emisor::Cols::_llave_password = "\"llave_password\"";
const std::string Emisor::Cols::_certificado_valido_desde = "\"certificado_valido_desde\"";
const std::string Emisor::Cols::_certificado_valido_hasta = "\"certificado_valido_hasta\"";
const std::string Emisor::Cols::_certificado_numero = "\"certificado_numero\"";
const std::string Emisor::Cols::_domicilio_fiscal = "\"domicilio_fiscal\"";
const std::string Emisor::primaryKeyName = "id";
const bool Emisor::hasPrimaryKey = true;
const std::string Emisor::tableName = "\"emisor\"";

const std::vector<typename Emisor::MetaData> Emisor::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"rfc","std::string","character varying",13,0,0,1},
{"nombre","std::string","character varying",255,0,0,1},
{"regimen_fiscal","std::string","character varying",3,0,0,1},
{"certificado","std::string","text",0,0,0,0},
{"llave","std::string","text",0,0,0,0},
{"certificado_nombre","std::string","character varying",255,0,0,0},
{"llave_nombre","std::string","character varying",255,0,0,0},
{"llave_password","std::string","character varying",255,0,0,0},
{"certificado_valido_desde","::trantor::Date","date",0,0,0,0},
{"certificado_valido_hasta","::trantor::Date","date",0,0,0,0},
{"certificado_numero","std::string","character varying",20,0,0,0},
{"domicilio_fiscal","std::string","character varying",5,0,0,0}
};
const std::string &Emisor::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Emisor::Emisor(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["rfc"].isNull())
        {
            rfc_=std::make_shared<std::string>(r["rfc"].as<std::string>());
        }
        if(!r["nombre"].isNull())
        {
            nombre_=std::make_shared<std::string>(r["nombre"].as<std::string>());
        }
        if(!r["regimen_fiscal"].isNull())
        {
            regimenFiscal_=std::make_shared<std::string>(r["regimen_fiscal"].as<std::string>());
        }
        if(!r["certificado"].isNull())
        {
            certificado_=std::make_shared<std::string>(r["certificado"].as<std::string>());
        }
        if(!r["llave"].isNull())
        {
            llave_=std::make_shared<std::string>(r["llave"].as<std::string>());
        }
        if(!r["certificado_nombre"].isNull())
        {
            certificadoNombre_=std::make_shared<std::string>(r["certificado_nombre"].as<std::string>());
        }
        if(!r["llave_nombre"].isNull())
        {
            llaveNombre_=std::make_shared<std::string>(r["llave_nombre"].as<std::string>());
        }
        if(!r["llave_password"].isNull())
        {
            llavePassword_=std::make_shared<std::string>(r["llave_password"].as<std::string>());
        }
        if(!r["certificado_valido_desde"].isNull())
        {
            auto daysStr = r["certificado_valido_desde"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            certificadoValidoDesde_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["certificado_valido_hasta"].isNull())
        {
            auto daysStr = r["certificado_valido_hasta"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            certificadoValidoHasta_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["certificado_numero"].isNull())
        {
            certificadoNumero_=std::make_shared<std::string>(r["certificado_numero"].as<std::string>());
        }
        if(!r["domicilio_fiscal"].isNull())
        {
            domicilioFiscal_=std::make_shared<std::string>(r["domicilio_fiscal"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 13 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            rfc_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            nombre_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            regimenFiscal_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            certificado_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            llave_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            certificadoNombre_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            llaveNombre_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            llavePassword_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            certificadoValidoDesde_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            certificadoValidoHasta_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            certificadoNumero_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            domicilioFiscal_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Emisor::Emisor(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            rfc_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            nombre_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            regimenFiscal_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            certificado_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            llave_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            certificadoNombre_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            llaveNombre_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            llavePassword_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            certificadoValidoDesde_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            certificadoValidoHasta_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            certificadoNumero_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            domicilioFiscal_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
}

Emisor::Emisor(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("rfc"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["rfc"].isNull())
        {
            rfc_=std::make_shared<std::string>(pJson["rfc"].asString());
        }
    }
    if(pJson.isMember("nombre"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["nombre"].isNull())
        {
            nombre_=std::make_shared<std::string>(pJson["nombre"].asString());
        }
    }
    if(pJson.isMember("regimen_fiscal"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["regimen_fiscal"].isNull())
        {
            regimenFiscal_=std::make_shared<std::string>(pJson["regimen_fiscal"].asString());
        }
    }
    if(pJson.isMember("certificado"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["certificado"].isNull())
        {
            certificado_=std::make_shared<std::string>(pJson["certificado"].asString());
        }
    }
    if(pJson.isMember("llave"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["llave"].isNull())
        {
            llave_=std::make_shared<std::string>(pJson["llave"].asString());
        }
    }
    if(pJson.isMember("certificado_nombre"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["certificado_nombre"].isNull())
        {
            certificadoNombre_=std::make_shared<std::string>(pJson["certificado_nombre"].asString());
        }
    }
    if(pJson.isMember("llave_nombre"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["llave_nombre"].isNull())
        {
            llaveNombre_=std::make_shared<std::string>(pJson["llave_nombre"].asString());
        }
    }
    if(pJson.isMember("llave_password"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["llave_password"].isNull())
        {
            llavePassword_=std::make_shared<std::string>(pJson["llave_password"].asString());
        }
    }
    if(pJson.isMember("certificado_valido_desde"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["certificado_valido_desde"].isNull())
        {
            auto daysStr = pJson["certificado_valido_desde"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            certificadoValidoDesde_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("certificado_valido_hasta"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["certificado_valido_hasta"].isNull())
        {
            auto daysStr = pJson["certificado_valido_hasta"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            certificadoValidoHasta_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("certificado_numero"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["certificado_numero"].isNull())
        {
            certificadoNumero_=std::make_shared<std::string>(pJson["certificado_numero"].asString());
        }
    }
    if(pJson.isMember("domicilio_fiscal"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["domicilio_fiscal"].isNull())
        {
            domicilioFiscal_=std::make_shared<std::string>(pJson["domicilio_fiscal"].asString());
        }
    }
}

void Emisor::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            rfc_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            nombre_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            regimenFiscal_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            certificado_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            llave_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            certificadoNombre_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            llaveNombre_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            llavePassword_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            certificadoValidoDesde_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            certificadoValidoHasta_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            certificadoNumero_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            domicilioFiscal_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
}

void Emisor::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("rfc"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["rfc"].isNull())
        {
            rfc_=std::make_shared<std::string>(pJson["rfc"].asString());
        }
    }
    if(pJson.isMember("nombre"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["nombre"].isNull())
        {
            nombre_=std::make_shared<std::string>(pJson["nombre"].asString());
        }
    }
    if(pJson.isMember("regimen_fiscal"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["regimen_fiscal"].isNull())
        {
            regimenFiscal_=std::make_shared<std::string>(pJson["regimen_fiscal"].asString());
        }
    }
    if(pJson.isMember("certificado"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["certificado"].isNull())
        {
            certificado_=std::make_shared<std::string>(pJson["certificado"].asString());
        }
    }
    if(pJson.isMember("llave"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["llave"].isNull())
        {
            llave_=std::make_shared<std::string>(pJson["llave"].asString());
        }
    }
    if(pJson.isMember("certificado_nombre"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["certificado_nombre"].isNull())
        {
            certificadoNombre_=std::make_shared<std::string>(pJson["certificado_nombre"].asString());
        }
    }
    if(pJson.isMember("llave_nombre"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["llave_nombre"].isNull())
        {
            llaveNombre_=std::make_shared<std::string>(pJson["llave_nombre"].asString());
        }
    }
    if(pJson.isMember("llave_password"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["llave_password"].isNull())
        {
            llavePassword_=std::make_shared<std::string>(pJson["llave_password"].asString());
        }
    }
    if(pJson.isMember("certificado_valido_desde"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["certificado_valido_desde"].isNull())
        {
            auto daysStr = pJson["certificado_valido_desde"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            certificadoValidoDesde_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("certificado_valido_hasta"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["certificado_valido_hasta"].isNull())
        {
            auto daysStr = pJson["certificado_valido_hasta"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            certificadoValidoHasta_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("certificado_numero"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["certificado_numero"].isNull())
        {
            certificadoNumero_=std::make_shared<std::string>(pJson["certificado_numero"].asString());
        }
    }
    if(pJson.isMember("domicilio_fiscal"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["domicilio_fiscal"].isNull())
        {
            domicilioFiscal_=std::make_shared<std::string>(pJson["domicilio_fiscal"].asString());
        }
    }
}

const int32_t &Emisor::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Emisor::getId() const noexcept
{
    return id_;
}
void Emisor::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Emisor::PrimaryKeyType & Emisor::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Emisor::getValueOfRfc() const noexcept
{
    static const std::string defaultValue = std::string();
    if(rfc_)
        return *rfc_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Emisor::getRfc() const noexcept
{
    return rfc_;
}
void Emisor::setRfc(const std::string &pRfc) noexcept
{
    rfc_ = std::make_shared<std::string>(pRfc);
    dirtyFlag_[1] = true;
}
void Emisor::setRfc(std::string &&pRfc) noexcept
{
    rfc_ = std::make_shared<std::string>(std::move(pRfc));
    dirtyFlag_[1] = true;
}

const std::string &Emisor::getValueOfNombre() const noexcept
{
    static const std::string defaultValue = std::string();
    if(nombre_)
        return *nombre_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Emisor::getNombre() const noexcept
{
    return nombre_;
}
void Emisor::setNombre(const std::string &pNombre) noexcept
{
    nombre_ = std::make_shared<std::string>(pNombre);
    dirtyFlag_[2] = true;
}
void Emisor::setNombre(std::string &&pNombre) noexcept
{
    nombre_ = std::make_shared<std::string>(std::move(pNombre));
    dirtyFlag_[2] = true;
}

const std::string &Emisor::getValueOfRegimenFiscal() const noexcept
{
    static const std::string defaultValue = std::string();
    if(regimenFiscal_)
        return *regimenFiscal_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Emisor::getRegimenFiscal() const noexcept
{
    return regimenFiscal_;
}
void Emisor::setRegimenFiscal(const std::string &pRegimenFiscal) noexcept
{
    regimenFiscal_ = std::make_shared<std::string>(pRegimenFiscal);
    dirtyFlag_[3] = true;
}
void Emisor::setRegimenFiscal(std::string &&pRegimenFiscal) noexcept
{
    regimenFiscal_ = std::make_shared<std::string>(std::move(pRegimenFiscal));
    dirtyFlag_[3] = true;
}

const std::string &Emisor::getValueOfCertificado() const noexcept
{
    static const std::string defaultValue = std::string();
    if(certificado_)
        return *certificado_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Emisor::getCertificado() const noexcept
{
    return certificado_;
}
void Emisor::setCertificado(const std::string &pCertificado) noexcept
{
    certificado_ = std::make_shared<std::string>(pCertificado);
    dirtyFlag_[4] = true;
}
void Emisor::setCertificado(std::string &&pCertificado) noexcept
{
    certificado_ = std::make_shared<std::string>(std::move(pCertificado));
    dirtyFlag_[4] = true;
}
void Emisor::setCertificadoToNull() noexcept
{
    certificado_.reset();
    dirtyFlag_[4] = true;
}

const std::string &Emisor::getValueOfLlave() const noexcept
{
    static const std::string defaultValue = std::string();
    if(llave_)
        return *llave_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Emisor::getLlave() const noexcept
{
    return llave_;
}
void Emisor::setLlave(const std::string &pLlave) noexcept
{
    llave_ = std::make_shared<std::string>(pLlave);
    dirtyFlag_[5] = true;
}
void Emisor::setLlave(std::string &&pLlave) noexcept
{
    llave_ = std::make_shared<std::string>(std::move(pLlave));
    dirtyFlag_[5] = true;
}
void Emisor::setLlaveToNull() noexcept
{
    llave_.reset();
    dirtyFlag_[5] = true;
}

const std::string &Emisor::getValueOfCertificadoNombre() const noexcept
{
    static const std::string defaultValue = std::string();
    if(certificadoNombre_)
        return *certificadoNombre_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Emisor::getCertificadoNombre() const noexcept
{
    return certificadoNombre_;
}
void Emisor::setCertificadoNombre(const std::string &pCertificadoNombre) noexcept
{
    certificadoNombre_ = std::make_shared<std::string>(pCertificadoNombre);
    dirtyFlag_[6] = true;
}
void Emisor::setCertificadoNombre(std::string &&pCertificadoNombre) noexcept
{
    certificadoNombre_ = std::make_shared<std::string>(std::move(pCertificadoNombre));
    dirtyFlag_[6] = true;
}
void Emisor::setCertificadoNombreToNull() noexcept
{
    certificadoNombre_.reset();
    dirtyFlag_[6] = true;
}

const std::string &Emisor::getValueOfLlaveNombre() const noexcept
{
    static const std::string defaultValue = std::string();
    if(llaveNombre_)
        return *llaveNombre_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Emisor::getLlaveNombre() const noexcept
{
    return llaveNombre_;
}
void Emisor::setLlaveNombre(const std::string &pLlaveNombre) noexcept
{
    llaveNombre_ = std::make_shared<std::string>(pLlaveNombre);
    dirtyFlag_[7] = true;
}
void Emisor::setLlaveNombre(std::string &&pLlaveNombre) noexcept
{
    llaveNombre_ = std::make_shared<std::string>(std::move(pLlaveNombre));
    dirtyFlag_[7] = true;
}
void Emisor::setLlaveNombreToNull() noexcept
{
    llaveNombre_.reset();
    dirtyFlag_[7] = true;
}

const std::string &Emisor::getValueOfLlavePassword() const noexcept
{
    static const std::string defaultValue = std::string();
    if(llavePassword_)
        return *llavePassword_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Emisor::getLlavePassword() const noexcept
{
    return llavePassword_;
}
void Emisor::setLlavePassword(const std::string &pLlavePassword) noexcept
{
    llavePassword_ = std::make_shared<std::string>(pLlavePassword);
    dirtyFlag_[8] = true;
}
void Emisor::setLlavePassword(std::string &&pLlavePassword) noexcept
{
    llavePassword_ = std::make_shared<std::string>(std::move(pLlavePassword));
    dirtyFlag_[8] = true;
}
void Emisor::setLlavePasswordToNull() noexcept
{
    llavePassword_.reset();
    dirtyFlag_[8] = true;
}

const ::trantor::Date &Emisor::getValueOfCertificadoValidoDesde() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(certificadoValidoDesde_)
        return *certificadoValidoDesde_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Emisor::getCertificadoValidoDesde() const noexcept
{
    return certificadoValidoDesde_;
}
void Emisor::setCertificadoValidoDesde(const ::trantor::Date &pCertificadoValidoDesde) noexcept
{
    certificadoValidoDesde_ = std::make_shared<::trantor::Date>(pCertificadoValidoDesde.roundDay());
    dirtyFlag_[9] = true;
}
void Emisor::setCertificadoValidoDesdeToNull() noexcept
{
    certificadoValidoDesde_.reset();
    dirtyFlag_[9] = true;
}

const ::trantor::Date &Emisor::getValueOfCertificadoValidoHasta() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(certificadoValidoHasta_)
        return *certificadoValidoHasta_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Emisor::getCertificadoValidoHasta() const noexcept
{
    return certificadoValidoHasta_;
}
void Emisor::setCertificadoValidoHasta(const ::trantor::Date &pCertificadoValidoHasta) noexcept
{
    certificadoValidoHasta_ = std::make_shared<::trantor::Date>(pCertificadoValidoHasta.roundDay());
    dirtyFlag_[10] = true;
}
void Emisor::setCertificadoValidoHastaToNull() noexcept
{
    certificadoValidoHasta_.reset();
    dirtyFlag_[10] = true;
}

const std::string &Emisor::getValueOfCertificadoNumero() const noexcept
{
    static const std::string defaultValue = std::string();
    if(certificadoNumero_)
        return *certificadoNumero_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Emisor::getCertificadoNumero() const noexcept
{
    return certificadoNumero_;
}
void Emisor::setCertificadoNumero(const std::string &pCertificadoNumero) noexcept
{
    certificadoNumero_ = std::make_shared<std::string>(pCertificadoNumero);
    dirtyFlag_[11] = true;
}
void Emisor::setCertificadoNumero(std::string &&pCertificadoNumero) noexcept
{
    certificadoNumero_ = std::make_shared<std::string>(std::move(pCertificadoNumero));
    dirtyFlag_[11] = true;
}
void Emisor::setCertificadoNumeroToNull() noexcept
{
    certificadoNumero_.reset();
    dirtyFlag_[11] = true;
}

const std::string &Emisor::getValueOfDomicilioFiscal() const noexcept
{
    static const std::string defaultValue = std::string();
    if(domicilioFiscal_)
        return *domicilioFiscal_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Emisor::getDomicilioFiscal() const noexcept
{
    return domicilioFiscal_;
}
void Emisor::setDomicilioFiscal(const std::string &pDomicilioFiscal) noexcept
{
    domicilioFiscal_ = std::make_shared<std::string>(pDomicilioFiscal);
    dirtyFlag_[12] = true;
}
void Emisor::setDomicilioFiscal(std::string &&pDomicilioFiscal) noexcept
{
    domicilioFiscal_ = std::make_shared<std::string>(std::move(pDomicilioFiscal));
    dirtyFlag_[12] = true;
}
void Emisor::setDomicilioFiscalToNull() noexcept
{
    domicilioFiscal_.reset();
    dirtyFlag_[12] = true;
}

void Emisor::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Emisor::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "rfc",
        "nombre",
        "regimen_fiscal",
        "certificado",
        "llave",
        "certificado_nombre",
        "llave_nombre",
        "llave_password",
        "certificado_valido_desde",
        "certificado_valido_hasta",
        "certificado_numero",
        "domicilio_fiscal"
    };
    return inCols;
}

void Emisor::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getRfc())
        {
            binder << getValueOfRfc();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getNombre())
        {
            binder << getValueOfNombre();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRegimenFiscal())
        {
            binder << getValueOfRegimenFiscal();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCertificado())
        {
            binder << getValueOfCertificado();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getLlave())
        {
            binder << getValueOfLlave();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCertificadoNombre())
        {
            binder << getValueOfCertificadoNombre();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getLlaveNombre())
        {
            binder << getValueOfLlaveNombre();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getLlavePassword())
        {
            binder << getValueOfLlavePassword();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getCertificadoValidoDesde())
        {
            binder << getValueOfCertificadoValidoDesde();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getCertificadoValidoHasta())
        {
            binder << getValueOfCertificadoValidoHasta();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getCertificadoNumero())
        {
            binder << getValueOfCertificadoNumero();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getDomicilioFiscal())
        {
            binder << getValueOfDomicilioFiscal();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Emisor::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    return ret;
}

void Emisor::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getRfc())
        {
            binder << getValueOfRfc();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getNombre())
        {
            binder << getValueOfNombre();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRegimenFiscal())
        {
            binder << getValueOfRegimenFiscal();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCertificado())
        {
            binder << getValueOfCertificado();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getLlave())
        {
            binder << getValueOfLlave();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCertificadoNombre())
        {
            binder << getValueOfCertificadoNombre();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getLlaveNombre())
        {
            binder << getValueOfLlaveNombre();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getLlavePassword())
        {
            binder << getValueOfLlavePassword();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getCertificadoValidoDesde())
        {
            binder << getValueOfCertificadoValidoDesde();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getCertificadoValidoHasta())
        {
            binder << getValueOfCertificadoValidoHasta();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getCertificadoNumero())
        {
            binder << getValueOfCertificadoNumero();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getDomicilioFiscal())
        {
            binder << getValueOfDomicilioFiscal();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Emisor::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getRfc())
    {
        ret["rfc"]=getValueOfRfc();
    }
    else
    {
        ret["rfc"]=Json::Value();
    }
    if(getNombre())
    {
        ret["nombre"]=getValueOfNombre();
    }
    else
    {
        ret["nombre"]=Json::Value();
    }
    if(getRegimenFiscal())
    {
        ret["regimen_fiscal"]=getValueOfRegimenFiscal();
    }
    else
    {
        ret["regimen_fiscal"]=Json::Value();
    }
    if(getCertificado())
    {
        ret["certificado"]=getValueOfCertificado();
    }
    else
    {
        ret["certificado"]=Json::Value();
    }
    if(getLlave())
    {
        ret["llave"]=getValueOfLlave();
    }
    else
    {
        ret["llave"]=Json::Value();
    }
    if(getCertificadoNombre())
    {
        ret["certificado_nombre"]=getValueOfCertificadoNombre();
    }
    else
    {
        ret["certificado_nombre"]=Json::Value();
    }
    if(getLlaveNombre())
    {
        ret["llave_nombre"]=getValueOfLlaveNombre();
    }
    else
    {
        ret["llave_nombre"]=Json::Value();
    }
    if(getLlavePassword())
    {
        ret["llave_password"]=getValueOfLlavePassword();
    }
    else
    {
        ret["llave_password"]=Json::Value();
    }
    if(getCertificadoValidoDesde())
    {
        ret["certificado_valido_desde"]=getCertificadoValidoDesde()->toDbStringLocal();
    }
    else
    {
        ret["certificado_valido_desde"]=Json::Value();
    }
    if(getCertificadoValidoHasta())
    {
        ret["certificado_valido_hasta"]=getCertificadoValidoHasta()->toDbStringLocal();
    }
    else
    {
        ret["certificado_valido_hasta"]=Json::Value();
    }
    if(getCertificadoNumero())
    {
        ret["certificado_numero"]=getValueOfCertificadoNumero();
    }
    else
    {
        ret["certificado_numero"]=Json::Value();
    }
    if(getDomicilioFiscal())
    {
        ret["domicilio_fiscal"]=getValueOfDomicilioFiscal();
    }
    else
    {
        ret["domicilio_fiscal"]=Json::Value();
    }
    return ret;
}

std::string Emisor::toString() const
{
    return toJson().toStyledString();
}

Json::Value Emisor::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 13)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getRfc())
            {
                ret[pMasqueradingVector[1]]=getValueOfRfc();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getNombre())
            {
                ret[pMasqueradingVector[2]]=getValueOfNombre();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getRegimenFiscal())
            {
                ret[pMasqueradingVector[3]]=getValueOfRegimenFiscal();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getCertificado())
            {
                ret[pMasqueradingVector[4]]=getValueOfCertificado();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getLlave())
            {
                ret[pMasqueradingVector[5]]=getValueOfLlave();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getCertificadoNombre())
            {
                ret[pMasqueradingVector[6]]=getValueOfCertificadoNombre();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getLlaveNombre())
            {
                ret[pMasqueradingVector[7]]=getValueOfLlaveNombre();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getLlavePassword())
            {
                ret[pMasqueradingVector[8]]=getValueOfLlavePassword();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getCertificadoValidoDesde())
            {
                ret[pMasqueradingVector[9]]=getCertificadoValidoDesde()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getCertificadoValidoHasta())
            {
                ret[pMasqueradingVector[10]]=getCertificadoValidoHasta()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getCertificadoNumero())
            {
                ret[pMasqueradingVector[11]]=getValueOfCertificadoNumero();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getDomicilioFiscal())
            {
                ret[pMasqueradingVector[12]]=getValueOfDomicilioFiscal();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getRfc())
    {
        ret["rfc"]=getValueOfRfc();
    }
    else
    {
        ret["rfc"]=Json::Value();
    }
    if(getNombre())
    {
        ret["nombre"]=getValueOfNombre();
    }
    else
    {
        ret["nombre"]=Json::Value();
    }
    if(getRegimenFiscal())
    {
        ret["regimen_fiscal"]=getValueOfRegimenFiscal();
    }
    else
    {
        ret["regimen_fiscal"]=Json::Value();
    }
    if(getCertificado())
    {
        ret["certificado"]=getValueOfCertificado();
    }
    else
    {
        ret["certificado"]=Json::Value();
    }
    if(getLlave())
    {
        ret["llave"]=getValueOfLlave();
    }
    else
    {
        ret["llave"]=Json::Value();
    }
    if(getCertificadoNombre())
    {
        ret["certificado_nombre"]=getValueOfCertificadoNombre();
    }
    else
    {
        ret["certificado_nombre"]=Json::Value();
    }
    if(getLlaveNombre())
    {
        ret["llave_nombre"]=getValueOfLlaveNombre();
    }
    else
    {
        ret["llave_nombre"]=Json::Value();
    }
    if(getLlavePassword())
    {
        ret["llave_password"]=getValueOfLlavePassword();
    }
    else
    {
        ret["llave_password"]=Json::Value();
    }
    if(getCertificadoValidoDesde())
    {
        ret["certificado_valido_desde"]=getCertificadoValidoDesde()->toDbStringLocal();
    }
    else
    {
        ret["certificado_valido_desde"]=Json::Value();
    }
    if(getCertificadoValidoHasta())
    {
        ret["certificado_valido_hasta"]=getCertificadoValidoHasta()->toDbStringLocal();
    }
    else
    {
        ret["certificado_valido_hasta"]=Json::Value();
    }
    if(getCertificadoNumero())
    {
        ret["certificado_numero"]=getValueOfCertificadoNumero();
    }
    else
    {
        ret["certificado_numero"]=Json::Value();
    }
    if(getDomicilioFiscal())
    {
        ret["domicilio_fiscal"]=getValueOfDomicilioFiscal();
    }
    else
    {
        ret["domicilio_fiscal"]=Json::Value();
    }
    return ret;
}

bool Emisor::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("rfc"))
    {
        if(!validJsonOfField(1, "rfc", pJson["rfc"], err, true))
            return false;
    }
    else
    {
        err="The rfc column cannot be null";
        return false;
    }
    if(pJson.isMember("nombre"))
    {
        if(!validJsonOfField(2, "nombre", pJson["nombre"], err, true))
            return false;
    }
    else
    {
        err="The nombre column cannot be null";
        return false;
    }
    if(pJson.isMember("regimen_fiscal"))
    {
        if(!validJsonOfField(3, "regimen_fiscal", pJson["regimen_fiscal"], err, true))
            return false;
    }
    else
    {
        err="The regimen_fiscal column cannot be null";
        return false;
    }
    if(pJson.isMember("certificado"))
    {
        if(!validJsonOfField(4, "certificado", pJson["certificado"], err, true))
            return false;
    }
    if(pJson.isMember("llave"))
    {
        if(!validJsonOfField(5, "llave", pJson["llave"], err, true))
            return false;
    }
    if(pJson.isMember("certificado_nombre"))
    {
        if(!validJsonOfField(6, "certificado_nombre", pJson["certificado_nombre"], err, true))
            return false;
    }
    if(pJson.isMember("llave_nombre"))
    {
        if(!validJsonOfField(7, "llave_nombre", pJson["llave_nombre"], err, true))
            return false;
    }
    if(pJson.isMember("llave_password"))
    {
        if(!validJsonOfField(8, "llave_password", pJson["llave_password"], err, true))
            return false;
    }
    if(pJson.isMember("certificado_valido_desde"))
    {
        if(!validJsonOfField(9, "certificado_valido_desde", pJson["certificado_valido_desde"], err, true))
            return false;
    }
    if(pJson.isMember("certificado_valido_hasta"))
    {
        if(!validJsonOfField(10, "certificado_valido_hasta", pJson["certificado_valido_hasta"], err, true))
            return false;
    }
    if(pJson.isMember("certificado_numero"))
    {
        if(!validJsonOfField(11, "certificado_numero", pJson["certificado_numero"], err, true))
            return false;
    }
    if(pJson.isMember("domicilio_fiscal"))
    {
        if(!validJsonOfField(12, "domicilio_fiscal", pJson["domicilio_fiscal"], err, true))
            return false;
    }
    return true;
}
bool Emisor::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Emisor::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("rfc"))
    {
        if(!validJsonOfField(1, "rfc", pJson["rfc"], err, false))
            return false;
    }
    if(pJson.isMember("nombre"))
    {
        if(!validJsonOfField(2, "nombre", pJson["nombre"], err, false))
            return false;
    }
    if(pJson.isMember("regimen_fiscal"))
    {
        if(!validJsonOfField(3, "regimen_fiscal", pJson["regimen_fiscal"], err, false))
            return false;
    }
    if(pJson.isMember("certificado"))
    {
        if(!validJsonOfField(4, "certificado", pJson["certificado"], err, false))
            return false;
    }
    if(pJson.isMember("llave"))
    {
        if(!validJsonOfField(5, "llave", pJson["llave"], err, false))
            return false;
    }
    if(pJson.isMember("certificado_nombre"))
    {
        if(!validJsonOfField(6, "certificado_nombre", pJson["certificado_nombre"], err, false))
            return false;
    }
    if(pJson.isMember("llave_nombre"))
    {
        if(!validJsonOfField(7, "llave_nombre", pJson["llave_nombre"], err, false))
            return false;
    }
    if(pJson.isMember("llave_password"))
    {
        if(!validJsonOfField(8, "llave_password", pJson["llave_password"], err, false))
            return false;
    }
    if(pJson.isMember("certificado_valido_desde"))
    {
        if(!validJsonOfField(9, "certificado_valido_desde", pJson["certificado_valido_desde"], err, false))
            return false;
    }
    if(pJson.isMember("certificado_valido_hasta"))
    {
        if(!validJsonOfField(10, "certificado_valido_hasta", pJson["certificado_valido_hasta"], err, false))
            return false;
    }
    if(pJson.isMember("certificado_numero"))
    {
        if(!validJsonOfField(11, "certificado_numero", pJson["certificado_numero"], err, false))
            return false;
    }
    if(pJson.isMember("domicilio_fiscal"))
    {
        if(!validJsonOfField(12, "domicilio_fiscal", pJson["domicilio_fiscal"], err, false))
            return false;
    }
    return true;
}
bool Emisor::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                              const std::vector<std::string> &pMasqueradingVector,
                                              std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Emisor::validJsonOfField(size_t index,
                              const std::string &fieldName,
                              const Json::Value &pJson,
                              std::string &err,
                              bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 13)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 13)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 3)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 3)";
                return false;
            }

            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }

            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 5)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 5)";
                return false;
            }

            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
