/**
 *
 *  Factura.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace admingas
{

class Factura
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _emisor_id;
        static const std::string _emisor_rfc;
        static const std::string _emisor_nombre;
        static const std::string _emisor_regimen_fiscal;
        static const std::string _receptor_id;
        static const std::string _receptor_rfc;
        static const std::string _receptor_nombre;
        static const std::string _receptor_domicilio_fiscal;
        static const std::string _receptor_regimen_fiscal;
        static const std::string _receptor_uso_cfdi;
        static const std::string _fecha;
        static const std::string _subtotal;
        static const std::string _impuestos;
        static const std::string _total;
        static const std::string _conceptos;
        static const std::string _xml_timbrado;
        static const std::string _uuid;
        static const std::string _sello;
        static const std::string _status;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Factura(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Factura(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Factura(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Factura() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int32_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int32_t &pId) noexcept;

    /**  For column emisor_id  */
    ///Get the value of the column emisor_id, returns the default value if the column is null
    const int32_t &getValueOfEmisorId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getEmisorId() const noexcept;
    ///Set the value of the column emisor_id
    void setEmisorId(const int32_t &pEmisorId) noexcept;
    void setEmisorIdToNull() noexcept;

    /**  For column emisor_rfc  */
    ///Get the value of the column emisor_rfc, returns the default value if the column is null
    const std::string &getValueOfEmisorRfc() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getEmisorRfc() const noexcept;
    ///Set the value of the column emisor_rfc
    void setEmisorRfc(const std::string &pEmisorRfc) noexcept;
    void setEmisorRfc(std::string &&pEmisorRfc) noexcept;

    /**  For column emisor_nombre  */
    ///Get the value of the column emisor_nombre, returns the default value if the column is null
    const std::string &getValueOfEmisorNombre() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getEmisorNombre() const noexcept;
    ///Set the value of the column emisor_nombre
    void setEmisorNombre(const std::string &pEmisorNombre) noexcept;
    void setEmisorNombre(std::string &&pEmisorNombre) noexcept;

    /**  For column emisor_regimen_fiscal  */
    ///Get the value of the column emisor_regimen_fiscal, returns the default value if the column is null
    const std::string &getValueOfEmisorRegimenFiscal() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getEmisorRegimenFiscal() const noexcept;
    ///Set the value of the column emisor_regimen_fiscal
    void setEmisorRegimenFiscal(const std::string &pEmisorRegimenFiscal) noexcept;
    void setEmisorRegimenFiscal(std::string &&pEmisorRegimenFiscal) noexcept;

    /**  For column receptor_id  */
    ///Get the value of the column receptor_id, returns the default value if the column is null
    const int32_t &getValueOfReceptorId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getReceptorId() const noexcept;
    ///Set the value of the column receptor_id
    void setReceptorId(const int32_t &pReceptorId) noexcept;
    void setReceptorIdToNull() noexcept;

    /**  For column receptor_rfc  */
    ///Get the value of the column receptor_rfc, returns the default value if the column is null
    const std::string &getValueOfReceptorRfc() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getReceptorRfc() const noexcept;
    ///Set the value of the column receptor_rfc
    void setReceptorRfc(const std::string &pReceptorRfc) noexcept;
    void setReceptorRfc(std::string &&pReceptorRfc) noexcept;

    /**  For column receptor_nombre  */
    ///Get the value of the column receptor_nombre, returns the default value if the column is null
    const std::string &getValueOfReceptorNombre() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getReceptorNombre() const noexcept;
    ///Set the value of the column receptor_nombre
    void setReceptorNombre(const std::string &pReceptorNombre) noexcept;
    void setReceptorNombre(std::string &&pReceptorNombre) noexcept;

    /**  For column receptor_domicilio_fiscal  */
    ///Get the value of the column receptor_domicilio_fiscal, returns the default value if the column is null
    const std::string &getValueOfReceptorDomicilioFiscal() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getReceptorDomicilioFiscal() const noexcept;
    ///Set the value of the column receptor_domicilio_fiscal
    void setReceptorDomicilioFiscal(const std::string &pReceptorDomicilioFiscal) noexcept;
    void setReceptorDomicilioFiscal(std::string &&pReceptorDomicilioFiscal) noexcept;

    /**  For column receptor_regimen_fiscal  */
    ///Get the value of the column receptor_regimen_fiscal, returns the default value if the column is null
    const std::string &getValueOfReceptorRegimenFiscal() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getReceptorRegimenFiscal() const noexcept;
    ///Set the value of the column receptor_regimen_fiscal
    void setReceptorRegimenFiscal(const std::string &pReceptorRegimenFiscal) noexcept;
    void setReceptorRegimenFiscal(std::string &&pReceptorRegimenFiscal) noexcept;

    /**  For column receptor_uso_cfdi  */
    ///Get the value of the column receptor_uso_cfdi, returns the default value if the column is null
    const std::string &getValueOfReceptorUsoCfdi() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getReceptorUsoCfdi() const noexcept;
    ///Set the value of the column receptor_uso_cfdi
    void setReceptorUsoCfdi(const std::string &pReceptorUsoCfdi) noexcept;
    void setReceptorUsoCfdi(std::string &&pReceptorUsoCfdi) noexcept;

    /**  For column fecha  */
    ///Get the value of the column fecha, returns the default value if the column is null
    const ::trantor::Date &getValueOfFecha() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getFecha() const noexcept;
    ///Set the value of the column fecha
    void setFecha(const ::trantor::Date &pFecha) noexcept;

    /**  For column subtotal  */
    ///Get the value of the column subtotal, returns the default value if the column is null
    const double &getValueOfSubtotal() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<double> &getSubtotal() const noexcept;
    ///Set the value of the column subtotal
    void setSubtotal(const double &pSubtotal) noexcept;

    /**  For column impuestos  */
    ///Get the value of the column impuestos, returns the default value if the column is null
    const double &getValueOfImpuestos() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<double> &getImpuestos() const noexcept;
    ///Set the value of the column impuestos
    void setImpuestos(const double &pImpuestos) noexcept;

    /**  For column total  */
    ///Get the value of the column total, returns the default value if the column is null
    const double &getValueOfTotal() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<double> &getTotal() const noexcept;
    ///Set the value of the column total
    void setTotal(const double &pTotal) noexcept;

    /**  For column conceptos  */
    ///Get the value of the column conceptos, returns the default value if the column is null
    const std::string &getValueOfConceptos() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getConceptos() const noexcept;
    ///Set the value of the column conceptos
    void setConceptos(const std::string &pConceptos) noexcept;
    void setConceptos(std::string &&pConceptos) noexcept;

    /**  For column xml_timbrado  */
    ///Get the value of the column xml_timbrado, returns the default value if the column is null
    const std::string &getValueOfXmlTimbrado() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getXmlTimbrado() const noexcept;
    ///Set the value of the column xml_timbrado
    void setXmlTimbrado(const std::string &pXmlTimbrado) noexcept;
    void setXmlTimbrado(std::string &&pXmlTimbrado) noexcept;
    void setXmlTimbradoToNull() noexcept;

    /**  For column uuid  */
    ///Get the value of the column uuid, returns the default value if the column is null
    const std::string &getValueOfUuid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUuid() const noexcept;
    ///Set the value of the column uuid
    void setUuid(const std::string &pUuid) noexcept;
    void setUuid(std::string &&pUuid) noexcept;
    void setUuidToNull() noexcept;

    /**  For column sello  */
    ///Get the value of the column sello, returns the default value if the column is null
    const std::string &getValueOfSello() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSello() const noexcept;
    ///Set the value of the column sello
    void setSello(const std::string &pSello) noexcept;
    void setSello(std::string &&pSello) noexcept;
    void setSelloToNull() noexcept;

    /**  For column status  */
    ///Get the value of the column status, returns the default value if the column is null
    const std::string &getValueOfStatus() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStatus() const noexcept;
    ///Set the value of the column status
    void setStatus(const std::string &pStatus) noexcept;
    void setStatus(std::string &&pStatus) noexcept;
    void setStatusToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 20;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Factura>;
    friend drogon::orm::BaseBuilder<Factura, true, true>;
    friend drogon::orm::BaseBuilder<Factura, true, false>;
    friend drogon::orm::BaseBuilder<Factura, false, true>;
    friend drogon::orm::BaseBuilder<Factura, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Factura>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> id_;
    std::shared_ptr<int32_t> emisorId_;
    std::shared_ptr<std::string> emisorRfc_;
    std::shared_ptr<std::string> emisorNombre_;
    std::shared_ptr<std::string> emisorRegimenFiscal_;
    std::shared_ptr<int32_t> receptorId_;
    std::shared_ptr<std::string> receptorRfc_;
    std::shared_ptr<std::string> receptorNombre_;
    std::shared_ptr<std::string> receptorDomicilioFiscal_;
    std::shared_ptr<std::string> receptorRegimenFiscal_;
    std::shared_ptr<std::string> receptorUsoCfdi_;
    std::shared_ptr<::trantor::Date> fecha_;
    std::shared_ptr<double> subtotal_;
    std::shared_ptr<double> impuestos_;
    std::shared_ptr<double> total_;
    std::shared_ptr<std::string> conceptos_;
    std::shared_ptr<std::string> xmlTimbrado_;
    std::shared_ptr<std::string> uuid_;
    std::shared_ptr<std::string> sello_;
    std::shared_ptr<std::string> status_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[20]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "emisor_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "emisor_rfc,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "emisor_nombre,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "emisor_regimen_fiscal,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "receptor_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "receptor_rfc,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "receptor_nombre,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "receptor_domicilio_fiscal,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "receptor_regimen_fiscal,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "receptor_uso_cfdi,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "fecha,";
            ++parametersCount;
        }
        if(dirtyFlag_[12])
        {
            sql += "subtotal,";
            ++parametersCount;
        }
        if(dirtyFlag_[13])
        {
            sql += "impuestos,";
            ++parametersCount;
        }
        if(dirtyFlag_[14])
        {
            sql += "total,";
            ++parametersCount;
        }
        if(dirtyFlag_[15])
        {
            sql += "conceptos,";
            ++parametersCount;
        }
        if(dirtyFlag_[16])
        {
            sql += "xml_timbrado,";
            ++parametersCount;
        }
        if(dirtyFlag_[17])
        {
            sql += "uuid,";
            ++parametersCount;
        }
        if(dirtyFlag_[18])
        {
            sql += "sello,";
            ++parametersCount;
        }
        sql += "status,";
        ++parametersCount;
        if(!dirtyFlag_[19])
        {
            needSelection=true;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[12])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[13])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[14])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[15])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[16])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[17])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[18])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[19])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace admingas
} // namespace drogon_model
