/**
 *
 *  Factura.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Factura.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::admingas;

const std::string Factura::Cols::_id = "\"id\"";
const std::string Factura::Cols::_emisor_id = "\"emisor_id\"";
const std::string Factura::Cols::_emisor_rfc = "\"emisor_rfc\"";
const std::string Factura::Cols::_emisor_nombre = "\"emisor_nombre\"";
const std::string Factura::Cols::_emisor_regimen_fiscal = "\"emisor_regimen_fiscal\"";
const std::string Factura::Cols::_receptor_id = "\"receptor_id\"";
const std::string Factura::Cols::_receptor_rfc = "\"receptor_rfc\"";
const std::string Factura::Cols::_receptor_nombre = "\"receptor_nombre\"";
const std::string Factura::Cols::_receptor_domicilio_fiscal = "\"receptor_domicilio_fiscal\"";
const std::string Factura::Cols::_receptor_regimen_fiscal = "\"receptor_regimen_fiscal\"";
const std::string Factura::Cols::_receptor_uso_cfdi = "\"receptor_uso_cfdi\"";
const std::string Factura::Cols::_fecha = "\"fecha\"";
const std::string Factura::Cols::_subtotal = "\"subtotal\"";
const std::string Factura::Cols::_impuestos = "\"impuestos\"";
const std::string Factura::Cols::_total = "\"total\"";
const std::string Factura::Cols::_conceptos = "\"conceptos\"";
const std::string Factura::Cols::_xml_timbrado = "\"xml_timbrado\"";
const std::string Factura::Cols::_uuid = "\"uuid\"";
const std::string Factura::Cols::_sello = "\"sello\"";
const std::string Factura::Cols::_status = "\"status\"";
const std::string Factura::primaryKeyName = "id";
const bool Factura::hasPrimaryKey = true;
const std::string Factura::tableName = "\"factura\"";

const std::vector<typename Factura::MetaData> Factura::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"emisor_id","int32_t","integer",4,0,0,0},
{"emisor_rfc","std::string","character varying",13,0,0,1},
{"emisor_nombre","std::string","character varying",255,0,0,1},
{"emisor_regimen_fiscal","std::string","character varying",3,0,0,1},
{"receptor_id","int32_t","integer",4,0,0,0},
{"receptor_rfc","std::string","character varying",13,0,0,1},
{"receptor_nombre","std::string","character varying",255,0,0,1},
{"receptor_domicilio_fiscal","std::string","character varying",5,0,0,1},
{"receptor_regimen_fiscal","std::string","character varying",3,0,0,1},
{"receptor_uso_cfdi","std::string","character varying",3,0,0,1},
{"fecha","::trantor::Date","date",0,0,0,1},
{"subtotal","double","double precision",8,0,0,1},
{"impuestos","double","double precision",8,0,0,1},
{"total","double","double precision",8,0,0,1},
{"conceptos","std::string","jsonb",0,0,0,1},
{"xml_timbrado","std::string","text",0,0,0,0},
{"uuid","std::string","character varying",36,0,0,0},
{"sello","std::string","character varying",500,0,0,0},
{"status","std::string","character varying",20,0,0,0}
};
const std::string &Factura::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Factura::Factura(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["emisor_id"].isNull())
        {
            emisorId_=std::make_shared<int32_t>(r["emisor_id"].as<int32_t>());
        }
        if(!r["emisor_rfc"].isNull())
        {
            emisorRfc_=std::make_shared<std::string>(r["emisor_rfc"].as<std::string>());
        }
        if(!r["emisor_nombre"].isNull())
        {
            emisorNombre_=std::make_shared<std::string>(r["emisor_nombre"].as<std::string>());
        }
        if(!r["emisor_regimen_fiscal"].isNull())
        {
            emisorRegimenFiscal_=std::make_shared<std::string>(r["emisor_regimen_fiscal"].as<std::string>());
        }
        if(!r["receptor_id"].isNull())
        {
            receptorId_=std::make_shared<int32_t>(r["receptor_id"].as<int32_t>());
        }
        if(!r["receptor_rfc"].isNull())
        {
            receptorRfc_=std::make_shared<std::string>(r["receptor_rfc"].as<std::string>());
        }
        if(!r["receptor_nombre"].isNull())
        {
            receptorNombre_=std::make_shared<std::string>(r["receptor_nombre"].as<std::string>());
        }
        if(!r["receptor_domicilio_fiscal"].isNull())
        {
            receptorDomicilioFiscal_=std::make_shared<std::string>(r["receptor_domicilio_fiscal"].as<std::string>());
        }
        if(!r["receptor_regimen_fiscal"].isNull())
        {
            receptorRegimenFiscal_=std::make_shared<std::string>(r["receptor_regimen_fiscal"].as<std::string>());
        }
        if(!r["receptor_uso_cfdi"].isNull())
        {
            receptorUsoCfdi_=std::make_shared<std::string>(r["receptor_uso_cfdi"].as<std::string>());
        }
        if(!r["fecha"].isNull())
        {
            auto daysStr = r["fecha"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            fecha_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["subtotal"].isNull())
        {
            subtotal_=std::make_shared<double>(r["subtotal"].as<double>());
        }
        if(!r["impuestos"].isNull())
        {
            impuestos_=std::make_shared<double>(r["impuestos"].as<double>());
        }
        if(!r["total"].isNull())
        {
            total_=std::make_shared<double>(r["total"].as<double>());
        }
        if(!r["conceptos"].isNull())
        {
            conceptos_=std::make_shared<std::string>(r["conceptos"].as<std::string>());
        }
        if(!r["xml_timbrado"].isNull())
        {
            xmlTimbrado_=std::make_shared<std::string>(r["xml_timbrado"].as<std::string>());
        }
        if(!r["uuid"].isNull())
        {
            uuid_=std::make_shared<std::string>(r["uuid"].as<std::string>());
        }
        if(!r["sello"].isNull())
        {
            sello_=std::make_shared<std::string>(r["sello"].as<std::string>());
        }
        if(!r["status"].isNull())
        {
            status_=std::make_shared<std::string>(r["status"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 20 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            emisorId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            emisorRfc_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            emisorNombre_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            emisorRegimenFiscal_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            receptorId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            receptorRfc_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            receptorNombre_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            receptorDomicilioFiscal_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            receptorRegimenFiscal_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            receptorUsoCfdi_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            fecha_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            subtotal_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            impuestos_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 14;
        if(!r[index].isNull())
        {
            total_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 15;
        if(!r[index].isNull())
        {
            conceptos_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 16;
        if(!r[index].isNull())
        {
            xmlTimbrado_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 17;
        if(!r[index].isNull())
        {
            uuid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 18;
        if(!r[index].isNull())
        {
            sello_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 19;
        if(!r[index].isNull())
        {
            status_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Factura::Factura(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 20)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            emisorId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            emisorRfc_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            emisorNombre_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            emisorRegimenFiscal_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            receptorId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            receptorRfc_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            receptorNombre_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            receptorDomicilioFiscal_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            receptorRegimenFiscal_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            receptorUsoCfdi_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[11]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            fecha_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            subtotal_=std::make_shared<double>(pJson[pMasqueradingVector[12]].asDouble());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            impuestos_=std::make_shared<double>(pJson[pMasqueradingVector[13]].asDouble());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            total_=std::make_shared<double>(pJson[pMasqueradingVector[14]].asDouble());
        }
    }
    if(!pMasqueradingVector[15].empty() && pJson.isMember(pMasqueradingVector[15]))
    {
        dirtyFlag_[15] = true;
        if(!pJson[pMasqueradingVector[15]].isNull())
        {
            conceptos_=std::make_shared<std::string>(pJson[pMasqueradingVector[15]].asString());
        }
    }
    if(!pMasqueradingVector[16].empty() && pJson.isMember(pMasqueradingVector[16]))
    {
        dirtyFlag_[16] = true;
        if(!pJson[pMasqueradingVector[16]].isNull())
        {
            xmlTimbrado_=std::make_shared<std::string>(pJson[pMasqueradingVector[16]].asString());
        }
    }
    if(!pMasqueradingVector[17].empty() && pJson.isMember(pMasqueradingVector[17]))
    {
        dirtyFlag_[17] = true;
        if(!pJson[pMasqueradingVector[17]].isNull())
        {
            uuid_=std::make_shared<std::string>(pJson[pMasqueradingVector[17]].asString());
        }
    }
    if(!pMasqueradingVector[18].empty() && pJson.isMember(pMasqueradingVector[18]))
    {
        dirtyFlag_[18] = true;
        if(!pJson[pMasqueradingVector[18]].isNull())
        {
            sello_=std::make_shared<std::string>(pJson[pMasqueradingVector[18]].asString());
        }
    }
    if(!pMasqueradingVector[19].empty() && pJson.isMember(pMasqueradingVector[19]))
    {
        dirtyFlag_[19] = true;
        if(!pJson[pMasqueradingVector[19]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[19]].asString());
        }
    }
}

Factura::Factura(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("emisor_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["emisor_id"].isNull())
        {
            emisorId_=std::make_shared<int32_t>((int32_t)pJson["emisor_id"].asInt64());
        }
    }
    if(pJson.isMember("emisor_rfc"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["emisor_rfc"].isNull())
        {
            emisorRfc_=std::make_shared<std::string>(pJson["emisor_rfc"].asString());
        }
    }
    if(pJson.isMember("emisor_nombre"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["emisor_nombre"].isNull())
        {
            emisorNombre_=std::make_shared<std::string>(pJson["emisor_nombre"].asString());
        }
    }
    if(pJson.isMember("emisor_regimen_fiscal"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["emisor_regimen_fiscal"].isNull())
        {
            emisorRegimenFiscal_=std::make_shared<std::string>(pJson["emisor_regimen_fiscal"].asString());
        }
    }
    if(pJson.isMember("receptor_id"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["receptor_id"].isNull())
        {
            receptorId_=std::make_shared<int32_t>((int32_t)pJson["receptor_id"].asInt64());
        }
    }
    if(pJson.isMember("receptor_rfc"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["receptor_rfc"].isNull())
        {
            receptorRfc_=std::make_shared<std::string>(pJson["receptor_rfc"].asString());
        }
    }
    if(pJson.isMember("receptor_nombre"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["receptor_nombre"].isNull())
        {
            receptorNombre_=std::make_shared<std::string>(pJson["receptor_nombre"].asString());
        }
    }
    if(pJson.isMember("receptor_domicilio_fiscal"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["receptor_domicilio_fiscal"].isNull())
        {
            receptorDomicilioFiscal_=std::make_shared<std::string>(pJson["receptor_domicilio_fiscal"].asString());
        }
    }
    if(pJson.isMember("receptor_regimen_fiscal"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["receptor_regimen_fiscal"].isNull())
        {
            receptorRegimenFiscal_=std::make_shared<std::string>(pJson["receptor_regimen_fiscal"].asString());
        }
    }
    if(pJson.isMember("receptor_uso_cfdi"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["receptor_uso_cfdi"].isNull())
        {
            receptorUsoCfdi_=std::make_shared<std::string>(pJson["receptor_uso_cfdi"].asString());
        }
    }
    if(pJson.isMember("fecha"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["fecha"].isNull())
        {
            auto daysStr = pJson["fecha"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            fecha_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("subtotal"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["subtotal"].isNull())
        {
            subtotal_=std::make_shared<double>(pJson["subtotal"].asDouble());
        }
    }
    if(pJson.isMember("impuestos"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["impuestos"].isNull())
        {
            impuestos_=std::make_shared<double>(pJson["impuestos"].asDouble());
        }
    }
    if(pJson.isMember("total"))
    {
        dirtyFlag_[14]=true;
        if(!pJson["total"].isNull())
        {
            total_=std::make_shared<double>(pJson["total"].asDouble());
        }
    }
    if(pJson.isMember("conceptos"))
    {
        dirtyFlag_[15]=true;
        if(!pJson["conceptos"].isNull())
        {
            conceptos_=std::make_shared<std::string>(pJson["conceptos"].asString());
        }
    }
    if(pJson.isMember("xml_timbrado"))
    {
        dirtyFlag_[16]=true;
        if(!pJson["xml_timbrado"].isNull())
        {
            xmlTimbrado_=std::make_shared<std::string>(pJson["xml_timbrado"].asString());
        }
    }
    if(pJson.isMember("uuid"))
    {
        dirtyFlag_[17]=true;
        if(!pJson["uuid"].isNull())
        {
            uuid_=std::make_shared<std::string>(pJson["uuid"].asString());
        }
    }
    if(pJson.isMember("sello"))
    {
        dirtyFlag_[18]=true;
        if(!pJson["sello"].isNull())
        {
            sello_=std::make_shared<std::string>(pJson["sello"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[19]=true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
}

void Factura::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 20)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            emisorId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            emisorRfc_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            emisorNombre_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            emisorRegimenFiscal_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            receptorId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            receptorRfc_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            receptorNombre_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            receptorDomicilioFiscal_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            receptorRegimenFiscal_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            receptorUsoCfdi_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[11]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            fecha_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            subtotal_=std::make_shared<double>(pJson[pMasqueradingVector[12]].asDouble());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            impuestos_=std::make_shared<double>(pJson[pMasqueradingVector[13]].asDouble());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            total_=std::make_shared<double>(pJson[pMasqueradingVector[14]].asDouble());
        }
    }
    if(!pMasqueradingVector[15].empty() && pJson.isMember(pMasqueradingVector[15]))
    {
        dirtyFlag_[15] = true;
        if(!pJson[pMasqueradingVector[15]].isNull())
        {
            conceptos_=std::make_shared<std::string>(pJson[pMasqueradingVector[15]].asString());
        }
    }
    if(!pMasqueradingVector[16].empty() && pJson.isMember(pMasqueradingVector[16]))
    {
        dirtyFlag_[16] = true;
        if(!pJson[pMasqueradingVector[16]].isNull())
        {
            xmlTimbrado_=std::make_shared<std::string>(pJson[pMasqueradingVector[16]].asString());
        }
    }
    if(!pMasqueradingVector[17].empty() && pJson.isMember(pMasqueradingVector[17]))
    {
        dirtyFlag_[17] = true;
        if(!pJson[pMasqueradingVector[17]].isNull())
        {
            uuid_=std::make_shared<std::string>(pJson[pMasqueradingVector[17]].asString());
        }
    }
    if(!pMasqueradingVector[18].empty() && pJson.isMember(pMasqueradingVector[18]))
    {
        dirtyFlag_[18] = true;
        if(!pJson[pMasqueradingVector[18]].isNull())
        {
            sello_=std::make_shared<std::string>(pJson[pMasqueradingVector[18]].asString());
        }
    }
    if(!pMasqueradingVector[19].empty() && pJson.isMember(pMasqueradingVector[19]))
    {
        dirtyFlag_[19] = true;
        if(!pJson[pMasqueradingVector[19]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[19]].asString());
        }
    }
}

void Factura::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("emisor_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["emisor_id"].isNull())
        {
            emisorId_=std::make_shared<int32_t>((int32_t)pJson["emisor_id"].asInt64());
        }
    }
    if(pJson.isMember("emisor_rfc"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["emisor_rfc"].isNull())
        {
            emisorRfc_=std::make_shared<std::string>(pJson["emisor_rfc"].asString());
        }
    }
    if(pJson.isMember("emisor_nombre"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["emisor_nombre"].isNull())
        {
            emisorNombre_=std::make_shared<std::string>(pJson["emisor_nombre"].asString());
        }
    }
    if(pJson.isMember("emisor_regimen_fiscal"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["emisor_regimen_fiscal"].isNull())
        {
            emisorRegimenFiscal_=std::make_shared<std::string>(pJson["emisor_regimen_fiscal"].asString());
        }
    }
    if(pJson.isMember("receptor_id"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["receptor_id"].isNull())
        {
            receptorId_=std::make_shared<int32_t>((int32_t)pJson["receptor_id"].asInt64());
        }
    }
    if(pJson.isMember("receptor_rfc"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["receptor_rfc"].isNull())
        {
            receptorRfc_=std::make_shared<std::string>(pJson["receptor_rfc"].asString());
        }
    }
    if(pJson.isMember("receptor_nombre"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["receptor_nombre"].isNull())
        {
            receptorNombre_=std::make_shared<std::string>(pJson["receptor_nombre"].asString());
        }
    }
    if(pJson.isMember("receptor_domicilio_fiscal"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["receptor_domicilio_fiscal"].isNull())
        {
            receptorDomicilioFiscal_=std::make_shared<std::string>(pJson["receptor_domicilio_fiscal"].asString());
        }
    }
    if(pJson.isMember("receptor_regimen_fiscal"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["receptor_regimen_fiscal"].isNull())
        {
            receptorRegimenFiscal_=std::make_shared<std::string>(pJson["receptor_regimen_fiscal"].asString());
        }
    }
    if(pJson.isMember("receptor_uso_cfdi"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["receptor_uso_cfdi"].isNull())
        {
            receptorUsoCfdi_=std::make_shared<std::string>(pJson["receptor_uso_cfdi"].asString());
        }
    }
    if(pJson.isMember("fecha"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["fecha"].isNull())
        {
            auto daysStr = pJson["fecha"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            fecha_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("subtotal"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["subtotal"].isNull())
        {
            subtotal_=std::make_shared<double>(pJson["subtotal"].asDouble());
        }
    }
    if(pJson.isMember("impuestos"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["impuestos"].isNull())
        {
            impuestos_=std::make_shared<double>(pJson["impuestos"].asDouble());
        }
    }
    if(pJson.isMember("total"))
    {
        dirtyFlag_[14] = true;
        if(!pJson["total"].isNull())
        {
            total_=std::make_shared<double>(pJson["total"].asDouble());
        }
    }
    if(pJson.isMember("conceptos"))
    {
        dirtyFlag_[15] = true;
        if(!pJson["conceptos"].isNull())
        {
            conceptos_=std::make_shared<std::string>(pJson["conceptos"].asString());
        }
    }
    if(pJson.isMember("xml_timbrado"))
    {
        dirtyFlag_[16] = true;
        if(!pJson["xml_timbrado"].isNull())
        {
            xmlTimbrado_=std::make_shared<std::string>(pJson["xml_timbrado"].asString());
        }
    }
    if(pJson.isMember("uuid"))
    {
        dirtyFlag_[17] = true;
        if(!pJson["uuid"].isNull())
        {
            uuid_=std::make_shared<std::string>(pJson["uuid"].asString());
        }
    }
    if(pJson.isMember("sello"))
    {
        dirtyFlag_[18] = true;
        if(!pJson["sello"].isNull())
        {
            sello_=std::make_shared<std::string>(pJson["sello"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[19] = true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
}

const int32_t &Factura::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Factura::getId() const noexcept
{
    return id_;
}
void Factura::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Factura::PrimaryKeyType & Factura::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t &Factura::getValueOfEmisorId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(emisorId_)
        return *emisorId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Factura::getEmisorId() const noexcept
{
    return emisorId_;
}
void Factura::setEmisorId(const int32_t &pEmisorId) noexcept
{
    emisorId_ = std::make_shared<int32_t>(pEmisorId);
    dirtyFlag_[1] = true;
}
void Factura::setEmisorIdToNull() noexcept
{
    emisorId_.reset();
    dirtyFlag_[1] = true;
}

const std::string &Factura::getValueOfEmisorRfc() const noexcept
{
    static const std::string defaultValue = std::string();
    if(emisorRfc_)
        return *emisorRfc_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Factura::getEmisorRfc() const noexcept
{
    return emisorRfc_;
}
void Factura::setEmisorRfc(const std::string &pEmisorRfc) noexcept
{
    emisorRfc_ = std::make_shared<std::string>(pEmisorRfc);
    dirtyFlag_[2] = true;
}
void Factura::setEmisorRfc(std::string &&pEmisorRfc) noexcept
{
    emisorRfc_ = std::make_shared<std::string>(std::move(pEmisorRfc));
    dirtyFlag_[2] = true;
}

const std::string &Factura::getValueOfEmisorNombre() const noexcept
{
    static const std::string defaultValue = std::string();
    if(emisorNombre_)
        return *emisorNombre_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Factura::getEmisorNombre() const noexcept
{
    return emisorNombre_;
}
void Factura::setEmisorNombre(const std::string &pEmisorNombre) noexcept
{
    emisorNombre_ = std::make_shared<std::string>(pEmisorNombre);
    dirtyFlag_[3] = true;
}
void Factura::setEmisorNombre(std::string &&pEmisorNombre) noexcept
{
    emisorNombre_ = std::make_shared<std::string>(std::move(pEmisorNombre));
    dirtyFlag_[3] = true;
}

const std::string &Factura::getValueOfEmisorRegimenFiscal() const noexcept
{
    static const std::string defaultValue = std::string();
    if(emisorRegimenFiscal_)
        return *emisorRegimenFiscal_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Factura::getEmisorRegimenFiscal() const noexcept
{
    return emisorRegimenFiscal_;
}
void Factura::setEmisorRegimenFiscal(const std::string &pEmisorRegimenFiscal) noexcept
{
    emisorRegimenFiscal_ = std::make_shared<std::string>(pEmisorRegimenFiscal);
    dirtyFlag_[4] = true;
}
void Factura::setEmisorRegimenFiscal(std::string &&pEmisorRegimenFiscal) noexcept
{
    emisorRegimenFiscal_ = std::make_shared<std::string>(std::move(pEmisorRegimenFiscal));
    dirtyFlag_[4] = true;
}

const int32_t &Factura::getValueOfReceptorId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(receptorId_)
        return *receptorId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Factura::getReceptorId() const noexcept
{
    return receptorId_;
}
void Factura::setReceptorId(const int32_t &pReceptorId) noexcept
{
    receptorId_ = std::make_shared<int32_t>(pReceptorId);
    dirtyFlag_[5] = true;
}
void Factura::setReceptorIdToNull() noexcept
{
    receptorId_.reset();
    dirtyFlag_[5] = true;
}

const std::string &Factura::getValueOfReceptorRfc() const noexcept
{
    static const std::string defaultValue = std::string();
    if(receptorRfc_)
        return *receptorRfc_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Factura::getReceptorRfc() const noexcept
{
    return receptorRfc_;
}
void Factura::setReceptorRfc(const std::string &pReceptorRfc) noexcept
{
    receptorRfc_ = std::make_shared<std::string>(pReceptorRfc);
    dirtyFlag_[6] = true;
}
void Factura::setReceptorRfc(std::string &&pReceptorRfc) noexcept
{
    receptorRfc_ = std::make_shared<std::string>(std::move(pReceptorRfc));
    dirtyFlag_[6] = true;
}

const std::string &Factura::getValueOfReceptorNombre() const noexcept
{
    static const std::string defaultValue = std::string();
    if(receptorNombre_)
        return *receptorNombre_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Factura::getReceptorNombre() const noexcept
{
    return receptorNombre_;
}
void Factura::setReceptorNombre(const std::string &pReceptorNombre) noexcept
{
    receptorNombre_ = std::make_shared<std::string>(pReceptorNombre);
    dirtyFlag_[7] = true;
}
void Factura::setReceptorNombre(std::string &&pReceptorNombre) noexcept
{
    receptorNombre_ = std::make_shared<std::string>(std::move(pReceptorNombre));
    dirtyFlag_[7] = true;
}

const std::string &Factura::getValueOfReceptorDomicilioFiscal() const noexcept
{
    static const std::string defaultValue = std::string();
    if(receptorDomicilioFiscal_)
        return *receptorDomicilioFiscal_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Factura::getReceptorDomicilioFiscal() const noexcept
{
    return receptorDomicilioFiscal_;
}
void Factura::setReceptorDomicilioFiscal(const std::string &pReceptorDomicilioFiscal) noexcept
{
    receptorDomicilioFiscal_ = std::make_shared<std::string>(pReceptorDomicilioFiscal);
    dirtyFlag_[8] = true;
}
void Factura::setReceptorDomicilioFiscal(std::string &&pReceptorDomicilioFiscal) noexcept
{
    receptorDomicilioFiscal_ = std::make_shared<std::string>(std::move(pReceptorDomicilioFiscal));
    dirtyFlag_[8] = true;
}

const std::string &Factura::getValueOfReceptorRegimenFiscal() const noexcept
{
    static const std::string defaultValue = std::string();
    if(receptorRegimenFiscal_)
        return *receptorRegimenFiscal_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Factura::getReceptorRegimenFiscal() const noexcept
{
    return receptorRegimenFiscal_;
}
void Factura::setReceptorRegimenFiscal(const std::string &pReceptorRegimenFiscal) noexcept
{
    receptorRegimenFiscal_ = std::make_shared<std::string>(pReceptorRegimenFiscal);
    dirtyFlag_[9] = true;
}
void Factura::setReceptorRegimenFiscal(std::string &&pReceptorRegimenFiscal) noexcept
{
    receptorRegimenFiscal_ = std::make_shared<std::string>(std::move(pReceptorRegimenFiscal));
    dirtyFlag_[9] = true;
}

const std::string &Factura::getValueOfReceptorUsoCfdi() const noexcept
{
    static const std::string defaultValue = std::string();
    if(receptorUsoCfdi_)
        return *receptorUsoCfdi_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Factura::getReceptorUsoCfdi() const noexcept
{
    return receptorUsoCfdi_;
}
void Factura::setReceptorUsoCfdi(const std::string &pReceptorUsoCfdi) noexcept
{
    receptorUsoCfdi_ = std::make_shared<std::string>(pReceptorUsoCfdi);
    dirtyFlag_[10] = true;
}
void Factura::setReceptorUsoCfdi(std::string &&pReceptorUsoCfdi) noexcept
{
    receptorUsoCfdi_ = std::make_shared<std::string>(std::move(pReceptorUsoCfdi));
    dirtyFlag_[10] = true;
}

const ::trantor::Date &Factura::getValueOfFecha() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(fecha_)
        return *fecha_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Factura::getFecha() const noexcept
{
    return fecha_;
}
void Factura::setFecha(const ::trantor::Date &pFecha) noexcept
{
    fecha_ = std::make_shared<::trantor::Date>(pFecha.roundDay());
    dirtyFlag_[11] = true;
}

const double &Factura::getValueOfSubtotal() const noexcept
{
    static const double defaultValue = double();
    if(subtotal_)
        return *subtotal_;
    return defaultValue;
}
const std::shared_ptr<double> &Factura::getSubtotal() const noexcept
{
    return subtotal_;
}
void Factura::setSubtotal(const double &pSubtotal) noexcept
{
    subtotal_ = std::make_shared<double>(pSubtotal);
    dirtyFlag_[12] = true;
}

const double &Factura::getValueOfImpuestos() const noexcept
{
    static const double defaultValue = double();
    if(impuestos_)
        return *impuestos_;
    return defaultValue;
}
const std::shared_ptr<double> &Factura::getImpuestos() const noexcept
{
    return impuestos_;
}
void Factura::setImpuestos(const double &pImpuestos) noexcept
{
    impuestos_ = std::make_shared<double>(pImpuestos);
    dirtyFlag_[13] = true;
}

const double &Factura::getValueOfTotal() const noexcept
{
    static const double defaultValue = double();
    if(total_)
        return *total_;
    return defaultValue;
}
const std::shared_ptr<double> &Factura::getTotal() const noexcept
{
    return total_;
}
void Factura::setTotal(const double &pTotal) noexcept
{
    total_ = std::make_shared<double>(pTotal);
    dirtyFlag_[14] = true;
}

const std::string &Factura::getValueOfConceptos() const noexcept
{
    static const std::string defaultValue = std::string();
    if(conceptos_)
        return *conceptos_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Factura::getConceptos() const noexcept
{
    return conceptos_;
}
void Factura::setConceptos(const std::string &pConceptos) noexcept
{
    conceptos_ = std::make_shared<std::string>(pConceptos);
    dirtyFlag_[15] = true;
}
void Factura::setConceptos(std::string &&pConceptos) noexcept
{
    conceptos_ = std::make_shared<std::string>(std::move(pConceptos));
    dirtyFlag_[15] = true;
}

const std::string &Factura::getValueOfXmlTimbrado() const noexcept
{
    static const std::string defaultValue = std::string();
    if(xmlTimbrado_)
        return *xmlTimbrado_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Factura::getXmlTimbrado() const noexcept
{
    return xmlTimbrado_;
}
void Factura::setXmlTimbrado(const std::string &pXmlTimbrado) noexcept
{
    xmlTimbrado_ = std::make_shared<std::string>(pXmlTimbrado);
    dirtyFlag_[16] = true;
}
void Factura::setXmlTimbrado(std::string &&pXmlTimbrado) noexcept
{
    xmlTimbrado_ = std::make_shared<std::string>(std::move(pXmlTimbrado));
    dirtyFlag_[16] = true;
}
void Factura::setXmlTimbradoToNull() noexcept
{
    xmlTimbrado_.reset();
    dirtyFlag_[16] = true;
}

const std::string &Factura::getValueOfUuid() const noexcept
{
    static const std::string defaultValue = std::string();
    if(uuid_)
        return *uuid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Factura::getUuid() const noexcept
{
    return uuid_;
}
void Factura::setUuid(const std::string &pUuid) noexcept
{
    uuid_ = std::make_shared<std::string>(pUuid);
    dirtyFlag_[17] = true;
}
void Factura::setUuid(std::string &&pUuid) noexcept
{
    uuid_ = std::make_shared<std::string>(std::move(pUuid));
    dirtyFlag_[17] = true;
}
void Factura::setUuidToNull() noexcept
{
    uuid_.reset();
    dirtyFlag_[17] = true;
}

const std::string &Factura::getValueOfSello() const noexcept
{
    static const std::string defaultValue = std::string();
    if(sello_)
        return *sello_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Factura::getSello() const noexcept
{
    return sello_;
}
void Factura::setSello(const std::string &pSello) noexcept
{
    sello_ = std::make_shared<std::string>(pSello);
    dirtyFlag_[18] = true;
}
void Factura::setSello(std::string &&pSello) noexcept
{
    sello_ = std::make_shared<std::string>(std::move(pSello));
    dirtyFlag_[18] = true;
}
void Factura::setSelloToNull() noexcept
{
    sello_.reset();
    dirtyFlag_[18] = true;
}

const std::string &Factura::getValueOfStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(status_)
        return *status_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Factura::getStatus() const noexcept
{
    return status_;
}
void Factura::setStatus(const std::string &pStatus) noexcept
{
    status_ = std::make_shared<std::string>(pStatus);
    dirtyFlag_[19] = true;
}
void Factura::setStatus(std::string &&pStatus) noexcept
{
    status_ = std::make_shared<std::string>(std::move(pStatus));
    dirtyFlag_[19] = true;
}
void Factura::setStatusToNull() noexcept
{
    status_.reset();
    dirtyFlag_[19] = true;
}

void Factura::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Factura::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "emisor_id",
        "emisor_rfc",
        "emisor_nombre",
        "emisor_regimen_fiscal",
        "receptor_id",
        "receptor_rfc",
        "receptor_nombre",
        "receptor_domicilio_fiscal",
        "receptor_regimen_fiscal",
        "receptor_uso_cfdi",
        "fecha",
        "subtotal",
        "impuestos",
        "total",
        "conceptos",
        "xml_timbrado",
        "uuid",
        "sello",
        "status"
    };
    return inCols;
}

void Factura::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getEmisorId())
        {
            binder << getValueOfEmisorId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getEmisorRfc())
        {
            binder << getValueOfEmisorRfc();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getEmisorNombre())
        {
            binder << getValueOfEmisorNombre();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getEmisorRegimenFiscal())
        {
            binder << getValueOfEmisorRegimenFiscal();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getReceptorId())
        {
            binder << getValueOfReceptorId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getReceptorRfc())
        {
            binder << getValueOfReceptorRfc();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getReceptorNombre())
        {
            binder << getValueOfReceptorNombre();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getReceptorDomicilioFiscal())
        {
            binder << getValueOfReceptorDomicilioFiscal();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getReceptorRegimenFiscal())
        {
            binder << getValueOfReceptorRegimenFiscal();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getReceptorUsoCfdi())
        {
            binder << getValueOfReceptorUsoCfdi();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getFecha())
        {
            binder << getValueOfFecha();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getSubtotal())
        {
            binder << getValueOfSubtotal();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getImpuestos())
        {
            binder << getValueOfImpuestos();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getTotal())
        {
            binder << getValueOfTotal();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[15])
    {
        if(getConceptos())
        {
            binder << getValueOfConceptos();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[16])
    {
        if(getXmlTimbrado())
        {
            binder << getValueOfXmlTimbrado();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[17])
    {
        if(getUuid())
        {
            binder << getValueOfUuid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[18])
    {
        if(getSello())
        {
            binder << getValueOfSello();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[19])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Factura::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    if(dirtyFlag_[14])
    {
        ret.push_back(getColumnName(14));
    }
    if(dirtyFlag_[15])
    {
        ret.push_back(getColumnName(15));
    }
    if(dirtyFlag_[16])
    {
        ret.push_back(getColumnName(16));
    }
    if(dirtyFlag_[17])
    {
        ret.push_back(getColumnName(17));
    }
    if(dirtyFlag_[18])
    {
        ret.push_back(getColumnName(18));
    }
    if(dirtyFlag_[19])
    {
        ret.push_back(getColumnName(19));
    }
    return ret;
}

void Factura::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getEmisorId())
        {
            binder << getValueOfEmisorId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getEmisorRfc())
        {
            binder << getValueOfEmisorRfc();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getEmisorNombre())
        {
            binder << getValueOfEmisorNombre();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getEmisorRegimenFiscal())
        {
            binder << getValueOfEmisorRegimenFiscal();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getReceptorId())
        {
            binder << getValueOfReceptorId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getReceptorRfc())
        {
            binder << getValueOfReceptorRfc();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getReceptorNombre())
        {
            binder << getValueOfReceptorNombre();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getReceptorDomicilioFiscal())
        {
            binder << getValueOfReceptorDomicilioFiscal();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getReceptorRegimenFiscal())
        {
            binder << getValueOfReceptorRegimenFiscal();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getReceptorUsoCfdi())
        {
            binder << getValueOfReceptorUsoCfdi();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getFecha())
        {
            binder << getValueOfFecha();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getSubtotal())
        {
            binder << getValueOfSubtotal();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getImpuestos())
        {
            binder << getValueOfImpuestos();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getTotal())
        {
            binder << getValueOfTotal();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[15])
    {
        if(getConceptos())
        {
            binder << getValueOfConceptos();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[16])
    {
        if(getXmlTimbrado())
        {
            binder << getValueOfXmlTimbrado();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[17])
    {
        if(getUuid())
        {
            binder << getValueOfUuid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[18])
    {
        if(getSello())
        {
            binder << getValueOfSello();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[19])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Factura::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getEmisorId())
    {
        ret["emisor_id"]=getValueOfEmisorId();
    }
    else
    {
        ret["emisor_id"]=Json::Value();
    }
    if(getEmisorRfc())
    {
        ret["emisor_rfc"]=getValueOfEmisorRfc();
    }
    else
    {
        ret["emisor_rfc"]=Json::Value();
    }
    if(getEmisorNombre())
    {
        ret["emisor_nombre"]=getValueOfEmisorNombre();
    }
    else
    {
        ret["emisor_nombre"]=Json::Value();
    }
    if(getEmisorRegimenFiscal())
    {
        ret["emisor_regimen_fiscal"]=getValueOfEmisorRegimenFiscal();
    }
    else
    {
        ret["emisor_regimen_fiscal"]=Json::Value();
    }
    if(getReceptorId())
    {
        ret["receptor_id"]=getValueOfReceptorId();
    }
    else
    {
        ret["receptor_id"]=Json::Value();
    }
    if(getReceptorRfc())
    {
        ret["receptor_rfc"]=getValueOfReceptorRfc();
    }
    else
    {
        ret["receptor_rfc"]=Json::Value();
    }
    if(getReceptorNombre())
    {
        ret["receptor_nombre"]=getValueOfReceptorNombre();
    }
    else
    {
        ret["receptor_nombre"]=Json::Value();
    }
    if(getReceptorDomicilioFiscal())
    {
        ret["receptor_domicilio_fiscal"]=getValueOfReceptorDomicilioFiscal();
    }
    else
    {
        ret["receptor_domicilio_fiscal"]=Json::Value();
    }
    if(getReceptorRegimenFiscal())
    {
        ret["receptor_regimen_fiscal"]=getValueOfReceptorRegimenFiscal();
    }
    else
    {
        ret["receptor_regimen_fiscal"]=Json::Value();
    }
    if(getReceptorUsoCfdi())
    {
        ret["receptor_uso_cfdi"]=getValueOfReceptorUsoCfdi();
    }
    else
    {
        ret["receptor_uso_cfdi"]=Json::Value();
    }
    if(getFecha())
    {
        ret["fecha"]=getFecha()->toDbStringLocal();
    }
    else
    {
        ret["fecha"]=Json::Value();
    }
    if(getSubtotal())
    {
        ret["subtotal"]=getValueOfSubtotal();
    }
    else
    {
        ret["subtotal"]=Json::Value();
    }
    if(getImpuestos())
    {
        ret["impuestos"]=getValueOfImpuestos();
    }
    else
    {
        ret["impuestos"]=Json::Value();
    }
    if(getTotal())
    {
        ret["total"]=getValueOfTotal();
    }
    else
    {
        ret["total"]=Json::Value();
    }
    if(getConceptos())
    {
        ret["conceptos"]=getValueOfConceptos();
    }
    else
    {
        ret["conceptos"]=Json::Value();
    }
    if(getXmlTimbrado())
    {
        ret["xml_timbrado"]=getValueOfXmlTimbrado();
    }
    else
    {
        ret["xml_timbrado"]=Json::Value();
    }
    if(getUuid())
    {
        ret["uuid"]=getValueOfUuid();
    }
    else
    {
        ret["uuid"]=Json::Value();
    }
    if(getSello())
    {
        ret["sello"]=getValueOfSello();
    }
    else
    {
        ret["sello"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    return ret;
}

std::string Factura::toString() const
{
    return toJson().toStyledString();
}

Json::Value Factura::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 20)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getEmisorId())
            {
                ret[pMasqueradingVector[1]]=getValueOfEmisorId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getEmisorRfc())
            {
                ret[pMasqueradingVector[2]]=getValueOfEmisorRfc();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getEmisorNombre())
            {
                ret[pMasqueradingVector[3]]=getValueOfEmisorNombre();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getEmisorRegimenFiscal())
            {
                ret[pMasqueradingVector[4]]=getValueOfEmisorRegimenFiscal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getReceptorId())
            {
                ret[pMasqueradingVector[5]]=getValueOfReceptorId();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getReceptorRfc())
            {
                ret[pMasqueradingVector[6]]=getValueOfReceptorRfc();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getReceptorNombre())
            {
                ret[pMasqueradingVector[7]]=getValueOfReceptorNombre();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getReceptorDomicilioFiscal())
            {
                ret[pMasqueradingVector[8]]=getValueOfReceptorDomicilioFiscal();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getReceptorRegimenFiscal())
            {
                ret[pMasqueradingVector[9]]=getValueOfReceptorRegimenFiscal();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getReceptorUsoCfdi())
            {
                ret[pMasqueradingVector[10]]=getValueOfReceptorUsoCfdi();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getFecha())
            {
                ret[pMasqueradingVector[11]]=getFecha()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getSubtotal())
            {
                ret[pMasqueradingVector[12]]=getValueOfSubtotal();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getImpuestos())
            {
                ret[pMasqueradingVector[13]]=getValueOfImpuestos();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[14].empty())
        {
            if(getTotal())
            {
                ret[pMasqueradingVector[14]]=getValueOfTotal();
            }
            else
            {
                ret[pMasqueradingVector[14]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[15].empty())
        {
            if(getConceptos())
            {
                ret[pMasqueradingVector[15]]=getValueOfConceptos();
            }
            else
            {
                ret[pMasqueradingVector[15]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[16].empty())
        {
            if(getXmlTimbrado())
            {
                ret[pMasqueradingVector[16]]=getValueOfXmlTimbrado();
            }
            else
            {
                ret[pMasqueradingVector[16]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[17].empty())
        {
            if(getUuid())
            {
                ret[pMasqueradingVector[17]]=getValueOfUuid();
            }
            else
            {
                ret[pMasqueradingVector[17]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[18].empty())
        {
            if(getSello())
            {
                ret[pMasqueradingVector[18]]=getValueOfSello();
            }
            else
            {
                ret[pMasqueradingVector[18]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[19].empty())
        {
            if(getStatus())
            {
                ret[pMasqueradingVector[19]]=getValueOfStatus();
            }
            else
            {
                ret[pMasqueradingVector[19]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getEmisorId())
    {
        ret["emisor_id"]=getValueOfEmisorId();
    }
    else
    {
        ret["emisor_id"]=Json::Value();
    }
    if(getEmisorRfc())
    {
        ret["emisor_rfc"]=getValueOfEmisorRfc();
    }
    else
    {
        ret["emisor_rfc"]=Json::Value();
    }
    if(getEmisorNombre())
    {
        ret["emisor_nombre"]=getValueOfEmisorNombre();
    }
    else
    {
        ret["emisor_nombre"]=Json::Value();
    }
    if(getEmisorRegimenFiscal())
    {
        ret["emisor_regimen_fiscal"]=getValueOfEmisorRegimenFiscal();
    }
    else
    {
        ret["emisor_regimen_fiscal"]=Json::Value();
    }
    if(getReceptorId())
    {
        ret["receptor_id"]=getValueOfReceptorId();
    }
    else
    {
        ret["receptor_id"]=Json::Value();
    }
    if(getReceptorRfc())
    {
        ret["receptor_rfc"]=getValueOfReceptorRfc();
    }
    else
    {
        ret["receptor_rfc"]=Json::Value();
    }
    if(getReceptorNombre())
    {
        ret["receptor_nombre"]=getValueOfReceptorNombre();
    }
    else
    {
        ret["receptor_nombre"]=Json::Value();
    }
    if(getReceptorDomicilioFiscal())
    {
        ret["receptor_domicilio_fiscal"]=getValueOfReceptorDomicilioFiscal();
    }
    else
    {
        ret["receptor_domicilio_fiscal"]=Json::Value();
    }
    if(getReceptorRegimenFiscal())
    {
        ret["receptor_regimen_fiscal"]=getValueOfReceptorRegimenFiscal();
    }
    else
    {
        ret["receptor_regimen_fiscal"]=Json::Value();
    }
    if(getReceptorUsoCfdi())
    {
        ret["receptor_uso_cfdi"]=getValueOfReceptorUsoCfdi();
    }
    else
    {
        ret["receptor_uso_cfdi"]=Json::Value();
    }
    if(getFecha())
    {
        ret["fecha"]=getFecha()->toDbStringLocal();
    }
    else
    {
        ret["fecha"]=Json::Value();
    }
    if(getSubtotal())
    {
        ret["subtotal"]=getValueOfSubtotal();
    }
    else
    {
        ret["subtotal"]=Json::Value();
    }
    if(getImpuestos())
    {
        ret["impuestos"]=getValueOfImpuestos();
    }
    else
    {
        ret["impuestos"]=Json::Value();
    }
    if(getTotal())
    {
        ret["total"]=getValueOfTotal();
    }
    else
    {
        ret["total"]=Json::Value();
    }
    if(getConceptos())
    {
        ret["conceptos"]=getValueOfConceptos();
    }
    else
    {
        ret["conceptos"]=Json::Value();
    }
    if(getXmlTimbrado())
    {
        ret["xml_timbrado"]=getValueOfXmlTimbrado();
    }
    else
    {
        ret["xml_timbrado"]=Json::Value();
    }
    if(getUuid())
    {
        ret["uuid"]=getValueOfUuid();
    }
    else
    {
        ret["uuid"]=Json::Value();
    }
    if(getSello())
    {
        ret["sello"]=getValueOfSello();
    }
    else
    {
        ret["sello"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    return ret;
}

bool Factura::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("emisor_id"))
    {
        if(!validJsonOfField(1, "emisor_id", pJson["emisor_id"], err, true))
            return false;
    }
    if(pJson.isMember("emisor_rfc"))
    {
        if(!validJsonOfField(2, "emisor_rfc", pJson["emisor_rfc"], err, true))
            return false;
    }
    else
    {
        err="The emisor_rfc column cannot be null";
        return false;
    }
    if(pJson.isMember("emisor_nombre"))
    {
        if(!validJsonOfField(3, "emisor_nombre", pJson["emisor_nombre"], err, true))
            return false;
    }
    else
    {
        err="The emisor_nombre column cannot be null";
        return false;
    }
    if(pJson.isMember("emisor_regimen_fiscal"))
    {
        if(!validJsonOfField(4, "emisor_regimen_fiscal", pJson["emisor_regimen_fiscal"], err, true))
            return false;
    }
    else
    {
        err="The emisor_regimen_fiscal column cannot be null";
        return false;
    }
    if(pJson.isMember("receptor_id"))
    {
        if(!validJsonOfField(5, "receptor_id", pJson["receptor_id"], err, true))
            return false;
    }
    if(pJson.isMember("receptor_rfc"))
    {
        if(!validJsonOfField(6, "receptor_rfc", pJson["receptor_rfc"], err, true))
            return false;
    }
    else
    {
        err="The receptor_rfc column cannot be null";
        return false;
    }
    if(pJson.isMember("receptor_nombre"))
    {
        if(!validJsonOfField(7, "receptor_nombre", pJson["receptor_nombre"], err, true))
            return false;
    }
    else
    {
        err="The receptor_nombre column cannot be null";
        return false;
    }
    if(pJson.isMember("receptor_domicilio_fiscal"))
    {
        if(!validJsonOfField(8, "receptor_domicilio_fiscal", pJson["receptor_domicilio_fiscal"], err, true))
            return false;
    }
    else
    {
        err="The receptor_domicilio_fiscal column cannot be null";
        return false;
    }
    if(pJson.isMember("receptor_regimen_fiscal"))
    {
        if(!validJsonOfField(9, "receptor_regimen_fiscal", pJson["receptor_regimen_fiscal"], err, true))
            return false;
    }
    else
    {
        err="The receptor_regimen_fiscal column cannot be null";
        return false;
    }
    if(pJson.isMember("receptor_uso_cfdi"))
    {
        if(!validJsonOfField(10, "receptor_uso_cfdi", pJson["receptor_uso_cfdi"], err, true))
            return false;
    }
    else
    {
        err="The receptor_uso_cfdi column cannot be null";
        return false;
    }
    if(pJson.isMember("fecha"))
    {
        if(!validJsonOfField(11, "fecha", pJson["fecha"], err, true))
            return false;
    }
    else
    {
        err="The fecha column cannot be null";
        return false;
    }
    if(pJson.isMember("subtotal"))
    {
        if(!validJsonOfField(12, "subtotal", pJson["subtotal"], err, true))
            return false;
    }
    else
    {
        err="The subtotal column cannot be null";
        return false;
    }
    if(pJson.isMember("impuestos"))
    {
        if(!validJsonOfField(13, "impuestos", pJson["impuestos"], err, true))
            return false;
    }
    else
    {
        err="The impuestos column cannot be null";
        return false;
    }
    if(pJson.isMember("total"))
    {
        if(!validJsonOfField(14, "total", pJson["total"], err, true))
            return false;
    }
    else
    {
        err="The total column cannot be null";
        return false;
    }
    if(pJson.isMember("conceptos"))
    {
        if(!validJsonOfField(15, "conceptos", pJson["conceptos"], err, true))
            return false;
    }
    else
    {
        err="The conceptos column cannot be null";
        return false;
    }
    if(pJson.isMember("xml_timbrado"))
    {
        if(!validJsonOfField(16, "xml_timbrado", pJson["xml_timbrado"], err, true))
            return false;
    }
    if(pJson.isMember("uuid"))
    {
        if(!validJsonOfField(17, "uuid", pJson["uuid"], err, true))
            return false;
    }
    if(pJson.isMember("sello"))
    {
        if(!validJsonOfField(18, "sello", pJson["sello"], err, true))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(19, "status", pJson["status"], err, true))
            return false;
    }
    return true;
}
bool Factura::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 20)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[7] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[8] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[9] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[10] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[11] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[12] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[13] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[14].empty())
      {
          if(pJson.isMember(pMasqueradingVector[14]))
          {
              if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[14] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[15].empty())
      {
          if(pJson.isMember(pMasqueradingVector[15]))
          {
              if(!validJsonOfField(15, pMasqueradingVector[15], pJson[pMasqueradingVector[15]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[15] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[16].empty())
      {
          if(pJson.isMember(pMasqueradingVector[16]))
          {
              if(!validJsonOfField(16, pMasqueradingVector[16], pJson[pMasqueradingVector[16]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[17].empty())
      {
          if(pJson.isMember(pMasqueradingVector[17]))
          {
              if(!validJsonOfField(17, pMasqueradingVector[17], pJson[pMasqueradingVector[17]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[18].empty())
      {
          if(pJson.isMember(pMasqueradingVector[18]))
          {
              if(!validJsonOfField(18, pMasqueradingVector[18], pJson[pMasqueradingVector[18]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[19].empty())
      {
          if(pJson.isMember(pMasqueradingVector[19]))
          {
              if(!validJsonOfField(19, pMasqueradingVector[19], pJson[pMasqueradingVector[19]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Factura::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("emisor_id"))
    {
        if(!validJsonOfField(1, "emisor_id", pJson["emisor_id"], err, false))
            return false;
    }
    if(pJson.isMember("emisor_rfc"))
    {
        if(!validJsonOfField(2, "emisor_rfc", pJson["emisor_rfc"], err, false))
            return false;
    }
    if(pJson.isMember("emisor_nombre"))
    {
        if(!validJsonOfField(3, "emisor_nombre", pJson["emisor_nombre"], err, false))
            return false;
    }
    if(pJson.isMember("emisor_regimen_fiscal"))
    {
        if(!validJsonOfField(4, "emisor_regimen_fiscal", pJson["emisor_regimen_fiscal"], err, false))
            return false;
    }
    if(pJson.isMember("receptor_id"))
    {
        if(!validJsonOfField(5, "receptor_id", pJson["receptor_id"], err, false))
            return false;
    }
    if(pJson.isMember("receptor_rfc"))
    {
        if(!validJsonOfField(6, "receptor_rfc", pJson["receptor_rfc"], err, false))
            return false;
    }
    if(pJson.isMember("receptor_nombre"))
    {
        if(!validJsonOfField(7, "receptor_nombre", pJson["receptor_nombre"], err, false))
            return false;
    }
    if(pJson.isMember("receptor_domicilio_fiscal"))
    {
        if(!validJsonOfField(8, "receptor_domicilio_fiscal", pJson["receptor_domicilio_fiscal"], err, false))
            return false;
    }
    if(pJson.isMember("receptor_regimen_fiscal"))
    {
        if(!validJsonOfField(9, "receptor_regimen_fiscal", pJson["receptor_regimen_fiscal"], err, false))
            return false;
    }
    if(pJson.isMember("receptor_uso_cfdi"))
    {
        if(!validJsonOfField(10, "receptor_uso_cfdi", pJson["receptor_uso_cfdi"], err, false))
            return false;
    }
    if(pJson.isMember("fecha"))
    {
        if(!validJsonOfField(11, "fecha", pJson["fecha"], err, false))
            return false;
    }
    if(pJson.isMember("subtotal"))
    {
        if(!validJsonOfField(12, "subtotal", pJson["subtotal"], err, false))
            return false;
    }
    if(pJson.isMember("impuestos"))
    {
        if(!validJsonOfField(13, "impuestos", pJson["impuestos"], err, false))
            return false;
    }
    if(pJson.isMember("total"))
    {
        if(!validJsonOfField(14, "total", pJson["total"], err, false))
            return false;
    }
    if(pJson.isMember("conceptos"))
    {
        if(!validJsonOfField(15, "conceptos", pJson["conceptos"], err, false))
            return false;
    }
    if(pJson.isMember("xml_timbrado"))
    {
        if(!validJsonOfField(16, "xml_timbrado", pJson["xml_timbrado"], err, false))
            return false;
    }
    if(pJson.isMember("uuid"))
    {
        if(!validJsonOfField(17, "uuid", pJson["uuid"], err, false))
            return false;
    }
    if(pJson.isMember("sello"))
    {
        if(!validJsonOfField(18, "sello", pJson["sello"], err, false))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(19, "status", pJson["status"], err, false))
            return false;
    }
    return true;
}
bool Factura::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 20)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
      if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
      {
          if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, false))
              return false;
      }
      if(!pMasqueradingVector[15].empty() && pJson.isMember(pMasqueradingVector[15]))
      {
          if(!validJsonOfField(15, pMasqueradingVector[15], pJson[pMasqueradingVector[15]], err, false))
              return false;
      }
      if(!pMasqueradingVector[16].empty() && pJson.isMember(pMasqueradingVector[16]))
      {
          if(!validJsonOfField(16, pMasqueradingVector[16], pJson[pMasqueradingVector[16]], err, false))
              return false;
      }
      if(!pMasqueradingVector[17].empty() && pJson.isMember(pMasqueradingVector[17]))
      {
          if(!validJsonOfField(17, pMasqueradingVector[17], pJson[pMasqueradingVector[17]], err, false))
              return false;
      }
      if(!pMasqueradingVector[18].empty() && pJson.isMember(pMasqueradingVector[18]))
      {
          if(!validJsonOfField(18, pMasqueradingVector[18], pJson[pMasqueradingVector[18]], err, false))
              return false;
      }
      if(!pMasqueradingVector[19].empty() && pJson.isMember(pMasqueradingVector[19]))
      {
          if(!validJsonOfField(19, pMasqueradingVector[19], pJson[pMasqueradingVector[19]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Factura::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson,
                               std::string &err,
                               bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 13)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 13)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 3)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 3)";
                return false;
            }

            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 13)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 13)";
                return false;
            }

            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 5)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 5)";
                return false;
            }

            break;
        case 9:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 3)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 3)";
                return false;
            }

            break;
        case 10:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 3)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 3)";
                return false;
            }

            break;
        case 11:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 13:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 14:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 15:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 16:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 17:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 36)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 36)";
                return false;
            }

            break;
        case 18:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 500)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 500)";
                return false;
            }

            break;
        case 19:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }

            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
