/**
 *
 *  Receptor.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Receptor.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::admingas;

const std::string Receptor::Cols::_id = "\"id\"";
const std::string Receptor::Cols::_rfc = "\"rfc\"";
const std::string Receptor::Cols::_nombre = "\"nombre\"";
const std::string Receptor::Cols::_domicilio_fiscal_receptor = "\"domicilio_fiscal_receptor\"";
const std::string Receptor::Cols::_regimen_fiscal_receptor = "\"regimen_fiscal_receptor\"";
const std::string Receptor::Cols::_uso_cfdi = "\"uso_cfdi\"";
const std::string Receptor::primaryKeyName = "id";
const bool Receptor::hasPrimaryKey = true;
const std::string Receptor::tableName = "\"receptor\"";

const std::vector<typename Receptor::MetaData> Receptor::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"rfc","std::string","character varying",13,0,0,1},
{"nombre","std::string","character varying",255,0,0,1},
{"domicilio_fiscal_receptor","std::string","character varying",5,0,0,1},
{"regimen_fiscal_receptor","std::string","character varying",3,0,0,1},
{"uso_cfdi","std::string","character varying",3,0,0,1}
};
const std::string &Receptor::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Receptor::Receptor(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["rfc"].isNull())
        {
            rfc_=std::make_shared<std::string>(r["rfc"].as<std::string>());
        }
        if(!r["nombre"].isNull())
        {
            nombre_=std::make_shared<std::string>(r["nombre"].as<std::string>());
        }
        if(!r["domicilio_fiscal_receptor"].isNull())
        {
            domicilioFiscalReceptor_=std::make_shared<std::string>(r["domicilio_fiscal_receptor"].as<std::string>());
        }
        if(!r["regimen_fiscal_receptor"].isNull())
        {
            regimenFiscalReceptor_=std::make_shared<std::string>(r["regimen_fiscal_receptor"].as<std::string>());
        }
        if(!r["uso_cfdi"].isNull())
        {
            usoCfdi_=std::make_shared<std::string>(r["uso_cfdi"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            rfc_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            nombre_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            domicilioFiscalReceptor_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            regimenFiscalReceptor_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            usoCfdi_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Receptor::Receptor(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            rfc_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            nombre_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            domicilioFiscalReceptor_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            regimenFiscalReceptor_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            usoCfdi_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
}

Receptor::Receptor(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("rfc"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["rfc"].isNull())
        {
            rfc_=std::make_shared<std::string>(pJson["rfc"].asString());
        }
    }
    if(pJson.isMember("nombre"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["nombre"].isNull())
        {
            nombre_=std::make_shared<std::string>(pJson["nombre"].asString());
        }
    }
    if(pJson.isMember("domicilio_fiscal_receptor"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["domicilio_fiscal_receptor"].isNull())
        {
            domicilioFiscalReceptor_=std::make_shared<std::string>(pJson["domicilio_fiscal_receptor"].asString());
        }
    }
    if(pJson.isMember("regimen_fiscal_receptor"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["regimen_fiscal_receptor"].isNull())
        {
            regimenFiscalReceptor_=std::make_shared<std::string>(pJson["regimen_fiscal_receptor"].asString());
        }
    }
    if(pJson.isMember("uso_cfdi"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["uso_cfdi"].isNull())
        {
            usoCfdi_=std::make_shared<std::string>(pJson["uso_cfdi"].asString());
        }
    }
}

void Receptor::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            rfc_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            nombre_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            domicilioFiscalReceptor_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            regimenFiscalReceptor_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            usoCfdi_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
}

void Receptor::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("rfc"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["rfc"].isNull())
        {
            rfc_=std::make_shared<std::string>(pJson["rfc"].asString());
        }
    }
    if(pJson.isMember("nombre"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["nombre"].isNull())
        {
            nombre_=std::make_shared<std::string>(pJson["nombre"].asString());
        }
    }
    if(pJson.isMember("domicilio_fiscal_receptor"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["domicilio_fiscal_receptor"].isNull())
        {
            domicilioFiscalReceptor_=std::make_shared<std::string>(pJson["domicilio_fiscal_receptor"].asString());
        }
    }
    if(pJson.isMember("regimen_fiscal_receptor"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["regimen_fiscal_receptor"].isNull())
        {
            regimenFiscalReceptor_=std::make_shared<std::string>(pJson["regimen_fiscal_receptor"].asString());
        }
    }
    if(pJson.isMember("uso_cfdi"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["uso_cfdi"].isNull())
        {
            usoCfdi_=std::make_shared<std::string>(pJson["uso_cfdi"].asString());
        }
    }
}

const int32_t &Receptor::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Receptor::getId() const noexcept
{
    return id_;
}
void Receptor::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Receptor::PrimaryKeyType & Receptor::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Receptor::getValueOfRfc() const noexcept
{
    static const std::string defaultValue = std::string();
    if(rfc_)
        return *rfc_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Receptor::getRfc() const noexcept
{
    return rfc_;
}
void Receptor::setRfc(const std::string &pRfc) noexcept
{
    rfc_ = std::make_shared<std::string>(pRfc);
    dirtyFlag_[1] = true;
}
void Receptor::setRfc(std::string &&pRfc) noexcept
{
    rfc_ = std::make_shared<std::string>(std::move(pRfc));
    dirtyFlag_[1] = true;
}

const std::string &Receptor::getValueOfNombre() const noexcept
{
    static const std::string defaultValue = std::string();
    if(nombre_)
        return *nombre_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Receptor::getNombre() const noexcept
{
    return nombre_;
}
void Receptor::setNombre(const std::string &pNombre) noexcept
{
    nombre_ = std::make_shared<std::string>(pNombre);
    dirtyFlag_[2] = true;
}
void Receptor::setNombre(std::string &&pNombre) noexcept
{
    nombre_ = std::make_shared<std::string>(std::move(pNombre));
    dirtyFlag_[2] = true;
}

const std::string &Receptor::getValueOfDomicilioFiscalReceptor() const noexcept
{
    static const std::string defaultValue = std::string();
    if(domicilioFiscalReceptor_)
        return *domicilioFiscalReceptor_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Receptor::getDomicilioFiscalReceptor() const noexcept
{
    return domicilioFiscalReceptor_;
}
void Receptor::setDomicilioFiscalReceptor(const std::string &pDomicilioFiscalReceptor) noexcept
{
    domicilioFiscalReceptor_ = std::make_shared<std::string>(pDomicilioFiscalReceptor);
    dirtyFlag_[3] = true;
}
void Receptor::setDomicilioFiscalReceptor(std::string &&pDomicilioFiscalReceptor) noexcept
{
    domicilioFiscalReceptor_ = std::make_shared<std::string>(std::move(pDomicilioFiscalReceptor));
    dirtyFlag_[3] = true;
}

const std::string &Receptor::getValueOfRegimenFiscalReceptor() const noexcept
{
    static const std::string defaultValue = std::string();
    if(regimenFiscalReceptor_)
        return *regimenFiscalReceptor_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Receptor::getRegimenFiscalReceptor() const noexcept
{
    return regimenFiscalReceptor_;
}
void Receptor::setRegimenFiscalReceptor(const std::string &pRegimenFiscalReceptor) noexcept
{
    regimenFiscalReceptor_ = std::make_shared<std::string>(pRegimenFiscalReceptor);
    dirtyFlag_[4] = true;
}
void Receptor::setRegimenFiscalReceptor(std::string &&pRegimenFiscalReceptor) noexcept
{
    regimenFiscalReceptor_ = std::make_shared<std::string>(std::move(pRegimenFiscalReceptor));
    dirtyFlag_[4] = true;
}

const std::string &Receptor::getValueOfUsoCfdi() const noexcept
{
    static const std::string defaultValue = std::string();
    if(usoCfdi_)
        return *usoCfdi_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Receptor::getUsoCfdi() const noexcept
{
    return usoCfdi_;
}
void Receptor::setUsoCfdi(const std::string &pUsoCfdi) noexcept
{
    usoCfdi_ = std::make_shared<std::string>(pUsoCfdi);
    dirtyFlag_[5] = true;
}
void Receptor::setUsoCfdi(std::string &&pUsoCfdi) noexcept
{
    usoCfdi_ = std::make_shared<std::string>(std::move(pUsoCfdi));
    dirtyFlag_[5] = true;
}

void Receptor::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Receptor::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "rfc",
        "nombre",
        "domicilio_fiscal_receptor",
        "regimen_fiscal_receptor",
        "uso_cfdi"
    };
    return inCols;
}

void Receptor::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getRfc())
        {
            binder << getValueOfRfc();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getNombre())
        {
            binder << getValueOfNombre();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDomicilioFiscalReceptor())
        {
            binder << getValueOfDomicilioFiscalReceptor();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getRegimenFiscalReceptor())
        {
            binder << getValueOfRegimenFiscalReceptor();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getUsoCfdi())
        {
            binder << getValueOfUsoCfdi();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Receptor::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void Receptor::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getRfc())
        {
            binder << getValueOfRfc();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getNombre())
        {
            binder << getValueOfNombre();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDomicilioFiscalReceptor())
        {
            binder << getValueOfDomicilioFiscalReceptor();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getRegimenFiscalReceptor())
        {
            binder << getValueOfRegimenFiscalReceptor();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getUsoCfdi())
        {
            binder << getValueOfUsoCfdi();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Receptor::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getRfc())
    {
        ret["rfc"]=getValueOfRfc();
    }
    else
    {
        ret["rfc"]=Json::Value();
    }
    if(getNombre())
    {
        ret["nombre"]=getValueOfNombre();
    }
    else
    {
        ret["nombre"]=Json::Value();
    }
    if(getDomicilioFiscalReceptor())
    {
        ret["domicilio_fiscal_receptor"]=getValueOfDomicilioFiscalReceptor();
    }
    else
    {
        ret["domicilio_fiscal_receptor"]=Json::Value();
    }
    if(getRegimenFiscalReceptor())
    {
        ret["regimen_fiscal_receptor"]=getValueOfRegimenFiscalReceptor();
    }
    else
    {
        ret["regimen_fiscal_receptor"]=Json::Value();
    }
    if(getUsoCfdi())
    {
        ret["uso_cfdi"]=getValueOfUsoCfdi();
    }
    else
    {
        ret["uso_cfdi"]=Json::Value();
    }
    return ret;
}

std::string Receptor::toString() const
{
    return toJson().toStyledString();
}

Json::Value Receptor::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getRfc())
            {
                ret[pMasqueradingVector[1]]=getValueOfRfc();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getNombre())
            {
                ret[pMasqueradingVector[2]]=getValueOfNombre();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getDomicilioFiscalReceptor())
            {
                ret[pMasqueradingVector[3]]=getValueOfDomicilioFiscalReceptor();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getRegimenFiscalReceptor())
            {
                ret[pMasqueradingVector[4]]=getValueOfRegimenFiscalReceptor();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getUsoCfdi())
            {
                ret[pMasqueradingVector[5]]=getValueOfUsoCfdi();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getRfc())
    {
        ret["rfc"]=getValueOfRfc();
    }
    else
    {
        ret["rfc"]=Json::Value();
    }
    if(getNombre())
    {
        ret["nombre"]=getValueOfNombre();
    }
    else
    {
        ret["nombre"]=Json::Value();
    }
    if(getDomicilioFiscalReceptor())
    {
        ret["domicilio_fiscal_receptor"]=getValueOfDomicilioFiscalReceptor();
    }
    else
    {
        ret["domicilio_fiscal_receptor"]=Json::Value();
    }
    if(getRegimenFiscalReceptor())
    {
        ret["regimen_fiscal_receptor"]=getValueOfRegimenFiscalReceptor();
    }
    else
    {
        ret["regimen_fiscal_receptor"]=Json::Value();
    }
    if(getUsoCfdi())
    {
        ret["uso_cfdi"]=getValueOfUsoCfdi();
    }
    else
    {
        ret["uso_cfdi"]=Json::Value();
    }
    return ret;
}

bool Receptor::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("rfc"))
    {
        if(!validJsonOfField(1, "rfc", pJson["rfc"], err, true))
            return false;
    }
    else
    {
        err="The rfc column cannot be null";
        return false;
    }
    if(pJson.isMember("nombre"))
    {
        if(!validJsonOfField(2, "nombre", pJson["nombre"], err, true))
            return false;
    }
    else
    {
        err="The nombre column cannot be null";
        return false;
    }
    if(pJson.isMember("domicilio_fiscal_receptor"))
    {
        if(!validJsonOfField(3, "domicilio_fiscal_receptor", pJson["domicilio_fiscal_receptor"], err, true))
            return false;
    }
    else
    {
        err="The domicilio_fiscal_receptor column cannot be null";
        return false;
    }
    if(pJson.isMember("regimen_fiscal_receptor"))
    {
        if(!validJsonOfField(4, "regimen_fiscal_receptor", pJson["regimen_fiscal_receptor"], err, true))
            return false;
    }
    else
    {
        err="The regimen_fiscal_receptor column cannot be null";
        return false;
    }
    if(pJson.isMember("uso_cfdi"))
    {
        if(!validJsonOfField(5, "uso_cfdi", pJson["uso_cfdi"], err, true))
            return false;
    }
    else
    {
        err="The uso_cfdi column cannot be null";
        return false;
    }
    return true;
}
bool Receptor::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Receptor::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("rfc"))
    {
        if(!validJsonOfField(1, "rfc", pJson["rfc"], err, false))
            return false;
    }
    if(pJson.isMember("nombre"))
    {
        if(!validJsonOfField(2, "nombre", pJson["nombre"], err, false))
            return false;
    }
    if(pJson.isMember("domicilio_fiscal_receptor"))
    {
        if(!validJsonOfField(3, "domicilio_fiscal_receptor", pJson["domicilio_fiscal_receptor"], err, false))
            return false;
    }
    if(pJson.isMember("regimen_fiscal_receptor"))
    {
        if(!validJsonOfField(4, "regimen_fiscal_receptor", pJson["regimen_fiscal_receptor"], err, false))
            return false;
    }
    if(pJson.isMember("uso_cfdi"))
    {
        if(!validJsonOfField(5, "uso_cfdi", pJson["uso_cfdi"], err, false))
            return false;
    }
    return true;
}
bool Receptor::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Receptor::validJsonOfField(size_t index,
                                const std::string &fieldName,
                                const Json::Value &pJson,
                                std::string &err,
                                bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 13)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 13)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 5)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 5)";
                return false;
            }

            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 3)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 3)";
                return false;
            }

            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 3)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 3)";
                return false;
            }

            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
