/**
 *
 *  Receptor.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace admingas
{

class Receptor
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _rfc;
        static const std::string _nombre;
        static const std::string _domicilio_fiscal_receptor;
        static const std::string _regimen_fiscal_receptor;
        static const std::string _uso_cfdi;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Receptor(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Receptor(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Receptor(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Receptor() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int32_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int32_t &pId) noexcept;

    /**  For column rfc  */
    ///Get the value of the column rfc, returns the default value if the column is null
    const std::string &getValueOfRfc() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRfc() const noexcept;
    ///Set the value of the column rfc
    void setRfc(const std::string &pRfc) noexcept;
    void setRfc(std::string &&pRfc) noexcept;

    /**  For column nombre  */
    ///Get the value of the column nombre, returns the default value if the column is null
    const std::string &getValueOfNombre() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getNombre() const noexcept;
    ///Set the value of the column nombre
    void setNombre(const std::string &pNombre) noexcept;
    void setNombre(std::string &&pNombre) noexcept;

    /**  For column domicilio_fiscal_receptor  */
    ///Get the value of the column domicilio_fiscal_receptor, returns the default value if the column is null
    const std::string &getValueOfDomicilioFiscalReceptor() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDomicilioFiscalReceptor() const noexcept;
    ///Set the value of the column domicilio_fiscal_receptor
    void setDomicilioFiscalReceptor(const std::string &pDomicilioFiscalReceptor) noexcept;
    void setDomicilioFiscalReceptor(std::string &&pDomicilioFiscalReceptor) noexcept;

    /**  For column regimen_fiscal_receptor  */
    ///Get the value of the column regimen_fiscal_receptor, returns the default value if the column is null
    const std::string &getValueOfRegimenFiscalReceptor() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRegimenFiscalReceptor() const noexcept;
    ///Set the value of the column regimen_fiscal_receptor
    void setRegimenFiscalReceptor(const std::string &pRegimenFiscalReceptor) noexcept;
    void setRegimenFiscalReceptor(std::string &&pRegimenFiscalReceptor) noexcept;

    /**  For column uso_cfdi  */
    ///Get the value of the column uso_cfdi, returns the default value if the column is null
    const std::string &getValueOfUsoCfdi() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUsoCfdi() const noexcept;
    ///Set the value of the column uso_cfdi
    void setUsoCfdi(const std::string &pUsoCfdi) noexcept;
    void setUsoCfdi(std::string &&pUsoCfdi) noexcept;


    static size_t getColumnNumber() noexcept {  return 6;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Receptor>;
    friend drogon::orm::BaseBuilder<Receptor, true, true>;
    friend drogon::orm::BaseBuilder<Receptor, true, false>;
    friend drogon::orm::BaseBuilder<Receptor, false, true>;
    friend drogon::orm::BaseBuilder<Receptor, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Receptor>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> id_;
    std::shared_ptr<std::string> rfc_;
    std::shared_ptr<std::string> nombre_;
    std::shared_ptr<std::string> domicilioFiscalReceptor_;
    std::shared_ptr<std::string> regimenFiscalReceptor_;
    std::shared_ptr<std::string> usoCfdi_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[6]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "rfc,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "nombre,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "domicilio_fiscal_receptor,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "regimen_fiscal_receptor,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "uso_cfdi,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace admingas
} // namespace drogon_model
